DATA LIST FREE /id sleep stress.
BEGIN DATA
1 5 10
2 6 9
3 6 8
4 7 7
5 7 6
6 8 5
7 8 4
8 9 3
END DATA.
DESCRIPTIVES VARIABLES=sleep stress
 /STATISTICS=MEAN STDDEV VARIANCE MIN MAX.
CORRELATIONS /VARIABLES=sleep stress
 /MISSING=LISTWISE.
