import React,{useEffect,useState,useCallback,lazy,Suspense} from 'react';
import {BookOpen,ChartColumn,ClipboardList,Library,Menu,X} from 'lucide-react';
import Home from './Home.jsx';
import Reader from './Reader.jsx';
const Lab=lazy(()=>import('./Lab.jsx'));
const Practice=lazy(()=>import('./Practice.jsx'));
const LibraryView=lazy(()=>import('./Library.jsx'));
import {loadProgress,saveProgress} from './storage.js';
import {number} from './format.js';
const nav=[['home','مسیر یادگیری',BookOpen],['lab','آزمایشگاه آمار',ChartColumn],['practice','بانک تمرین',ClipboardList],['library','کتابخانه',Library]];
function readRoute(){const params=new URLSearchParams(location.search),view=params.get('view')||'home',raw=Number(params.get('id')),id=Number.isInteger(raw)?raw:0;return {view:['home','lesson','lab','practice','library'].includes(view)?view:'home',id:view==='lesson'?Math.max(1,Math.min(10,id||1)):Math.max(0,Math.min(10,id))};}
export default function App(){
 const [course,setCourse]=useState(null),[error,setError]=useState(false),[route,setRoute]=useState(readRoute),[progress,setProgress]=useState(loadProgress),[menu,setMenu]=useState(false),[storageError,setStorageError]=useState(false);
 useEffect(()=>{fetch('/course.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(setCourse).catch(()=>setError(true));},[]);
 useEffect(()=>{setStorageError(!saveProgress(progress));},[progress]);
 useEffect(()=>{const handle=()=>{setRoute(readRoute());setMenu(false);};window.addEventListener('popstate',handle);return ()=>window.removeEventListener('popstate',handle);},[]);
 useEffect(()=>{if(!menu)return;const close=e=>{if(e.key==='Escape')setMenu(false);};window.addEventListener('keydown',close);return ()=>window.removeEventListener('keydown',close);},[menu]);
 const navigate=useCallback((view,id=0)=>{const query=view==='home'?location.pathname:`${location.pathname}?view=${view}${id?'&id='+id:''}`;history.pushState(null,'',query);setRoute({view,id});setMenu(false);window.scrollTo({top:0,behavior:'instant'});},[]);
 useEffect(()=>{if(!course||!document.modelContext?.registerTool)return;const lifecycle=new AbortController();const tool={name:'open_statistics_lesson',title:'بازکردن جلسهٔ آمار',description:'Open one of the ten statistics lessons in the visible learning interface. Does not mark it completed.',inputSchema:{type:'object',properties:{lessonId:{type:'integer',minimum:1,maximum:10}},required:['lessonId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){if(!input||Object.keys(input).some(k=>k!=='lessonId')||!Number.isInteger(input.lessonId)||input.lessonId<1||input.lessonId>10)throw Error('lessonId must be an integer from 1 to 10');navigate('lesson',input.lessonId);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {lessonId:input.lessonId,title:course.lessons[input.lessonId-1].title,opened:true};}};try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}return ()=>lifecycle.abort();},[course,navigate]);
 return <div className="app"><a className="skip-link" href="#main">رفتن به محتوا</a><aside className={'sidebar '+(menu?'open':'')}><a href="/" className="brand" onClick={e=>{e.preventDefault();navigate('home');}}><svg width="34" height="38" viewBox="0 0 34 38" aria-hidden="true"><path d="M6 31V24M17 31V15M28 31V5" stroke="#e9a83b" strokeWidth="7" strokeLinecap="round"/></svg><span>آمارآموز</span></a><nav aria-label="ناوبری اصلی">{nav.map(([view,label,Icon])=><button key={view} className={'nav-button '+((route.view==='lesson'&&view==='home'||route.view===view)?'active':'')} onClick={()=>navigate(view)}><Icon size={23}/><span>{label}</span></button>)}</nav><div className="course-progress"><strong>پیشرفت در دوره</strong><progress value={progress.lessons.length} max="10" aria-label="جلسه‌های خوانده‌شده"/><div><span>{number(progress.lessons.length)} از ۱۰ جلسه</span><span>{number(progress.lessons.length*10)}٪</span></div><small>{storageError?'ذخیره در این مرورگر در دسترس نیست':'ذخیره روی همین مرورگر'}</small></div></aside><div className="workspace"><header className="topbar"><button className="mobile-menu icon-button" aria-label={menu?'بستن منو':'باز کردن منو'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button><span>آمار توصیفی برای روان‌شناسی</span><span className="course-meta">۱۰ جلسه · ۴۸۰ تمرین</span></header><main id="main" tabIndex="-1">{error?<div className="empty-state"><h1>محتوا بارگذاری نشد</h1><p>اتصال را بررسی کنید و دوباره تلاش کنید.</p><button className="button" onClick={()=>location.reload()}>تلاش دوباره</button></div>:!course?<p role="status">در حال آماده‌کردن محتوای دوره…</p>:<Suspense fallback={<p role="status">در حال آماده‌کردن این بخش…</p>}>{route.view==='home'?<Home course={course} progress={progress} navigate={navigate}/>:route.view==='lesson'?<Reader key={route.id} lesson={course.lessons.find(l=>l.id===route.id)} progress={progress} setProgress={setProgress} navigate={navigate}/>:route.view==='lab'?<Lab/>:route.view==='practice'?<Practice key={route.id} course={course} initialLesson={route.id} progress={progress} setProgress={setProgress}/>:<LibraryView course={course} navigate={navigate}/>}</Suspense>}</main><footer>آمارآموز · محتوای تألیفی آمار توصیفی روان‌شناسی</footer></div>{menu?<button className="menu-overlay" aria-label="بستن منو" onClick={()=>setMenu(false)}/>:null}</div>;
}
