import React,{useId,useState} from 'react';
import {fmt,number} from './format.js';
import {histogram} from './stats.js';
const W=700,H=300,L=62,R=22,T=30,B=48;
function domain(lo,hi){const span=hi-lo;return span>0?[lo-span*.07,hi+span*.07]:[lo-1,hi+1];}
function Axis({xmin,xmax,ymin=0,ymax,xlabel,ylabel,children}){
 const sx=x=>L+(x-xmin)/(xmax-xmin)*(W-L-R),sy=y=>H-B-(y-ymin)/(ymax-ymin)*(H-T-B);
 return <svg viewBox={`0 0 ${W} ${H}`} className="data-chart" role="img" aria-label={xlabel+' در برابر '+ylabel}><g className="chart-grid">{Array.from({length:5},(_,i)=>{const y=ymin+(ymax-ymin)*i/4;return <g key={i}><line x1={L} x2={W-R} y1={sy(y)} y2={sy(y)}/><text x={L-12} y={sy(y)+5} textAnchor="end">{fmt(y)}</text></g>;})}</g><line className="chart-axis" x1={L} x2={W-R} y1={H-B} y2={H-B}/>{Array.from({length:5},(_,i)=>{const x=xmin+(xmax-xmin)*i/4;return <text key={i} x={sx(x)} y={H-B+22} textAnchor="middle">{fmt(x)}</text>;})}<text x={W/2} y={H-3} textAnchor="middle" className="chart-axis-label">{xlabel}</text><text transform={`translate(18 ${H/2}) rotate(-90)`} textAnchor="middle" className="chart-axis-label">{ylabel}</text>{children(sx,sy)}</svg>;
}
export function Histogram({values,stats,binCount}){
 const bins=histogram(values,binCount),[selected,setSelected]=useState(null);
 const max=Math.max(...bins.map(b=>b.count)),lo=bins[0].lo,hi=bins.at(-1).hi;
 const active=selected===null?null:bins[selected];
 return <><Axis xmin={lo} xmax={hi} ymax={Math.max(2,max+1)} xlabel="مقدار X" ylabel="فراوانی">{(sx,sy)=><>{bins.map((b,i)=><g key={i}><rect className="chart-bar" tabIndex="0" role="button" aria-label={'طبقهٔ '+number(i+1)+'، فراوانی '+number(b.count)} x={sx(b.lo)+1} y={sy(b.count)} width={Math.max(1,sx(b.hi)-sx(b.lo)-2)} height={sy(0)-sy(b.count)} fill={selected===i?'#e9a83b':'#28726a'} onClick={()=>setSelected(selected===i?null:i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(selected===i?null:i);}}}><title>{fmt(b.lo)} تا {fmt(b.hi)} · {number(b.count)} مشاهده</title></rect></g>)}<line x1={sx(stats.mean)} x2={sx(stats.mean)} y1={T} y2={H-B} stroke="#d79620" strokeWidth="2" strokeDasharray="6 5"/><line x1={sx(stats.median)} x2={sx(stats.median)} y1={T+12} y2={H-B} stroke="#113e3a" strokeWidth="2" strokeDasharray="2 4"/></>}</Axis><div className="chart-legend"><span><i className="legend-mean"/>میانگین {fmt(stats.mean)}</span><span><i className="legend-median"/>میانه {fmt(stats.median)}</span></div><p className="chart-interaction" aria-live="polite">{active?'طبقهٔ '+number(selected+1)+': '+number(active.count)+' مشاهده · '+(active.values.length?active.values.map(fmt).join('، '):'خالی'):'روی یک ستون کلیک کن تا داده‌های آن طبقه را ببینی.'}</p><div className="table-scroll"><table><thead><tr><th>طبقه</th><th>بازه</th><th>فراوانی</th><th>درصد</th><th>فراوانی تجمعی</th></tr></thead><tbody>{bins.map((b,i)=><tr key={i} className={selected===i?'selected-row':''}><td>{number(i+1)}</td><td dir="ltr">[{fmt(b.lo)}, {fmt(b.hi)}{i===bins.length-1?']':')'}</td><td>{number(b.count)}</td><td>{fmt(100*b.count/values.length)}٪</td><td>{number(bins.slice(0,i+1).reduce((s,b)=>s+b.count,0))}</td></tr>)}</tbody></table></div><p className="small-note">مرز پایین هر طبقه شامل می‌شود؛ مرز بالا فقط در آخرین طبقه شامل می‌شود. عددهای مرز برای نمایش گرد شده‌اند.</p></>;
}
export function BoxPlot({values,stats}){
 const [lo,hi]=domain(stats.min,stats.max),sx=v=>54+(v-lo)/(hi-lo)*592;
 return <><svg className="data-chart box-chart" viewBox="0 0 700 240" role="img" aria-label={`نمودار جعبه‌ای، میانه ${fmt(stats.median)}، چارک اول ${fmt(stats.q1)}، چارک سوم ${fmt(stats.q3)}`}><line x1="54" x2="646" y1="194" y2="194" className="chart-axis"/>{Array.from({length:5},(_,i)=>{const v=lo+(hi-lo)*i/4;return <text key={i} x={sx(v)} y="217" textAnchor="middle">{fmt(v)}</text>;})}<line x1={sx(stats.whiskerLow)} x2={sx(stats.whiskerHigh)} y1="104" y2="104" stroke="#28726a" strokeWidth="3"/>{[stats.whiskerLow,stats.whiskerHigh].map((v,i)=><line key={i} x1={sx(v)} x2={sx(v)} y1="84" y2="124" stroke="#28726a" strokeWidth="3"/>)}<rect x={sx(stats.q1)} y="70" width={Math.max(2,sx(stats.q3)-sx(stats.q1))} height="68" rx="5" fill="#dcece7" stroke="#28726a" strokeWidth="2"/><line x1={sx(stats.median)} x2={sx(stats.median)} y1="70" y2="138" stroke="#123f3a" strokeWidth="4"/><text x={sx(stats.median)} y="48" textAnchor="middle">میانه {fmt(stats.median)}</text><text x={sx(stats.q1)} y="159" textAnchor="middle">Q1: {fmt(stats.q1)}</text><text x={sx(stats.q3)} y="179" textAnchor="middle">Q3: {fmt(stats.q3)}</text>{stats.outliers.map((v,i)=><circle key={i} cx={sx(v)} cy={100+(i%3)*8} r="6" fill="#e9a83b" stroke="#9d681b"><title>دادهٔ دورافتاده: {fmt(v)}</title></circle>)}<text x="350" y="239" textAnchor="middle">مقدار X</text></svg><div className="chart-legend"><span><i className="legend-dot"/>دادهٔ دورافتاده با قاعدهٔ ۱٫۵ IQR</span></div><div className="metric-strip"><div><span>دامنهٔ میان‌چارکی</span><strong>{fmt(stats.iqr)}</strong></div><div><span>کرانهٔ پایین</span><strong>{fmt(stats.lower)}</strong></div><div><span>کرانهٔ بالا</span><strong>{fmt(stats.upper)}</strong></div><div><span>دادهٔ دورافتاده</span><strong>{number(stats.outliers.length)}</strong></div></div><p className="small-note">چارک‌ها با درون‌یابی خطی نوع ۷ (معادل PERCENTILE.INC) محاسبه می‌شوند. سبیل‌ها تا آخرین مقدار داخل کرانه‌ها امتداد دارند. دادهٔ دورافتاده خودکار حذف نمی‌شود.</p></>;
}
export function NormalChart({z}){
 const sx=v=>50+(v+4)/8*600,sy=v=>230-v*450;
 const path=Array.from({length:161},(_,i)=>{const x=-4+i*.05,y=Math.exp(-x*x/2)/Math.sqrt(2*Math.PI);return `${i?'L':'M'}${sx(x).toFixed(2)},${sy(y).toFixed(2)}`;}).join(' ');
 const clamped=z===null?null:Math.max(-4,Math.min(4,z));
 return <svg viewBox="0 0 700 280" className="data-chart" role="img" aria-label={z===null?'نمرهٔ استاندارد برای این داده‌ها تعریف‌نشده است':'نمرهٔ استاندارد '+fmt(z)+' روی منحنی مرجع نرمال'}><path d={path+' L650,230 L50,230 Z'} fill="#edf5f2"/><path d={path} fill="none" stroke="#28726a" strokeWidth="3"/><line x1="50" x2="650" y1="230" y2="230" className="chart-axis"/>{[-4,-3,-2,-1,0,1,2,3,4].map(n=><text key={n} x={sx(n)} y="254" textAnchor="middle">{fmt(n)}</text>)}<text x="350" y="277" textAnchor="middle">فاصله از میانگین برحسب انحراف معیار (z)</text>{clamped!==null?<><line x1={sx(clamped)} x2={sx(clamped)} y1="35" y2="230" stroke="#d99a29" strokeWidth="3" strokeDasharray="6 4"/><circle cx={sx(clamped)} cy={sy(Math.exp(-clamped*clamped/2)/Math.sqrt(2*Math.PI))} r="6" fill="#e9a83b"/><text className="z-marker-label" x={Math.max(140,Math.min(560,sx(clamped)))} y="24" textAnchor="middle" fill="#aa710c">z = {fmt(z)}{Math.abs(z)>4?' · خارج بازهٔ نمایش':''}</text></>:null}</svg>;
}
export function ScatterPlot({x,y,pair,showLine,selected,onSelect}){
 const [xmin,xmax]=domain(Math.min(...x),Math.max(...x)),[ymin,ymax]=domain(Math.min(...y),Math.max(...y)),clip=useId().replace(/:/g,'');
 return <Axis xmin={xmin} xmax={xmax} ymin={ymin} ymax={ymax} xlabel="متغیر X" ylabel="متغیر Y">{(sx,sy)=><><defs><clipPath id={clip}><rect x={L} y={T} width={W-L-R} height={H-T-B}/></clipPath></defs>{showLine&&pair.slope!==null?<line clipPath={`url(#${clip})`} x1={sx(xmin)} x2={sx(xmax)} y1={sy(pair.intercept+pair.slope*xmin)} y2={sy(pair.intercept+pair.slope*xmax)} stroke="#d69b32" strokeWidth="2.5" strokeDasharray="7 5"/>:null}{x.map((v,i)=><circle key={i} tabIndex="0" role="button" aria-label={'مشاهدهٔ '+number(i+1)+': X '+fmt(v)+'، Y '+fmt(y[i])} cx={sx(v)} cy={sy(y[i])} r={selected===i?9:6} fill={selected===i?'#e9a83b':'#28726a'} stroke="white" strokeWidth="2" onClick={()=>onSelect(selected===i?null:i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(selected===i?null:i);}}}><title>مشاهدهٔ {number(i+1)} · X={fmt(v)} · Y={fmt(y[i])}</title></circle>)}</>}</Axis>;
}
