import React from 'react';
import {ArrowLeft,RotateCcw,CheckCircle2,Lightbulb} from 'lucide-react';
import {coachedProblems,coachingSummary,stepPassed} from './coachedPractice.js';
import {number} from './format.js';

export default function CoachedPractice({state,dispatch,navigate,onOpenExercise}){
  const problem=coachedProblems.find(p=>p.id===state.selected),attempt=state.attempts[problem.id],index=attempt.active,step=problem.steps[index],answer=attempt.answers[index],result=attempt.results[index],summary=coachingSummary(attempt),passed=stepPassed(result);
  const move=action=>{dispatch(action);if(typeof window!=='undefined')requestAnimationFrame(()=>document.getElementById('coach-step-title')?.focus());};
  return <section className="coached-practice" id="coached-practice" tabIndex="-1" aria-labelledby="coach-title">
    <header className="coach-heading"><div><span className="lesson-eyebrow">روش، محاسبه، تفسیر</span><h2 id="coach-title">قدم‌به‌قدم حل کن</h2><p>شش تمرین منتخبِ بانک، با بررسی پاسخ هر گام و راهنمای مخصوص اشتباه‌ها.</p></div><label htmlFor="coach-problem">تمرین هدایت‌شده<select id="coach-problem" value={problem.id} onChange={e=>move({type:'select',id:e.target.value})}>{coachedProblems.map(p=><option key={p.id} value={p.id}>جلسهٔ {number(p.lessonId)} · {p.title}</option>)}</select></label></header>
    <div className="coach-layout"><aside className="coach-scenario"><span>صورت کامل · مثال ساختگی</span><h3>{problem.title}</h3><p>{problem.scenario}</p>{problem.y?<div className="table-scroll"><table><caption>هر سطر، یک فرد</caption><thead><tr><th scope="col">توجه</th><th scope="col">حافظه</th></tr></thead><tbody>{problem.data.map((value,i)=><tr key={i}><td>{number(value)}</td><td>{number(problem.y[i])}</td></tr>)}</tbody></table></div>:null}<ol className="coach-trail" aria-label="گام‌های تمرین">{problem.steps.map((item,i)=><li key={i} className={(i===index?'current ':'')+(stepPassed(attempt.results[i])?'passed':'')} aria-current={i===index?'step':undefined}><span>{stepPassed(attempt.results[i])?<CheckCircle2 size={18}/>:number(i+1)}</span><div>{item.title}{attempt.results[i]?.assisted||attempt.results[i]?.status==='assisted'?<small>با دیدن حل</small>:attempt.results[i]?.status==='correct'?<small>پاسخ بررسی‌شده</small>:null}</div></li>)}</ol><p className="coach-local-note">ورودی‌ها با تغییر تمرین در همین صفحه حفظ می‌شوند؛ با خروج یا بارگذاری دوباره، این مسیر از نو شروع می‌شود. وضعیت تمرین‌های بانک را خودت جداگانه ثبت می‌کنی.</p></aside>
      <div className="coach-work"><div className="coach-step-meta"><span>گام {number(index+1)} از {number(problem.steps.length)}</span><span>{number(summary.passed)} گام طی‌شده</span></div><h3 id="coach-step-title" tabIndex="-1">{step.title}</h3><form onSubmit={e=>{e.preventDefault();dispatch({type:'check'});}}><fieldset><legend>{step.prompt}</legend>{step.type==='choice'?<div className="coach-options">{step.options.map((option,i)=><label key={i} className={answer===i?'selected':''}><input type="radio" name={'coach-'+problem.id+'-'+index} checked={answer===i} onChange={()=>dispatch({type:'answer',value:i})}/><span>{option.text}</span></label>)}</div>:<div className="coach-number"><label htmlFor="coach-number">پاسخ عددی این گام<input id="coach-number" type="text" inputMode="decimal" value={answer} aria-invalid={result?.status==='invalid'} aria-describedby="coach-number-help" onChange={e=>dispatch({type:'answer',value:e.target.value})}/></label><p id="coach-number-help">فقط عدد؛ ارقام فارسی، منفی و اعشار تا شش رقم پذیرفته می‌شوند. مقدار باید بین منفی و مثبت ۱٬۰۰۰٬۰۰۰ باشد.</p></div>}</fieldset><button className="button" type="submit" disabled={answer===null||typeof answer==='string'&&answer.trim()===''||passed}>بررسی پاسخ این گام<CheckCircle2 size={18}/></button></form>
      {result?<div className={'coach-feedback '+(passed?'success':'retry')} role="status"><Lightbulb size={21}/><p>{result.message}{result.assisted?<small>{result.status==='correct'?'این پاسخ پس از نمایش حل بررسی شده است.':'این گام با راهنما طی شده؛ پاسخ مستقل بررسی نشده است.'}</small>:null}</p></div>:null}
      <details className="coach-hint" key={problem.id+'-'+index}><summary>راهنمای فکر؛ بدون دیدن جواب</summary><p>{step.hint}</p></details>
      <div className="coach-solution">{attempt.solutions[index]?<><h4>حل همین گام</h4><p aria-live="polite">{step.solution}</p>{!passed?<button className="text-button" onClick={()=>dispatch({type:'assist'})}>این گام را با راهنما گذراندم<ArrowLeft size={17}/></button>:null}</>:<button className="text-button" onClick={()=>dispatch({type:'reveal'})}>حل این گام را نشان بده</button>}</div>
      <div className="coach-navigation"><button className="button secondary compact" disabled={index===0} onClick={()=>move({type:'previous'})}>گام قبل</button>{index<problem.steps.length-1?<button className="button compact" disabled={!passed} onClick={()=>move({type:'next'})}>گام بعد<ArrowLeft size={17}/></button>:null}</div><p className="small-note">اگر پاسخ گام قبلی را تغییر بدهی، بررسی گام‌های بعدی پاک می‌شود و آن‌ها را دوباره بررسی می‌کنی.</p>
      {summary.complete?<div className="coach-complete" role="status"><CheckCircle2 size={25}/><div><h3>مسیر این تمرین را طی کردی.</h3><p>{number(summary.withoutSolution)} گام با پاسخ درست پیش از دیدن حل؛ {number(summary.assisted)} گام با دیدن حل.</p><p>برای آزمودن خودت، مسیر را دوباره بدون نمایش حل انجام بده و پاسخ کامل را در تمرین اصلی بنویس.</p></div></div>:null}
      <div className="coach-actions"><button className="text-button" onClick={()=>move({type:'reset'})}><RotateCcw size={17}/>شروع دوبارهٔ همین تمرین</button><button className="text-button" onClick={()=>navigate('lesson',problem.lessonId)}>مرور درس مرتبط<ArrowLeft size={17}/></button><button className="text-button" onClick={()=>onOpenExercise(problem.id)}>تمرین اصلی در بانک<ArrowLeft size={17}/></button></div>
      </div></div>
  </section>;
}
