import React,{useReducer} from 'react';
import {cumulativePresets,cumulativeChecks,initialCumulativeState,cumulativeReducer,analyzeCumulative,cumulativePercent,buildCumulativeReport} from './cumulative.js';
import {distributionValue,distributionAxisLabels} from './distributionComparison.js';
import {number} from './format.js';

export function CumulativePlot({summary:s,selected,onSelect}){
 const low=Math.min(s.sorted[0],s.threshold),high=Math.max(s.sorted.at(-1),s.threshold),pad=high>low?(high-low)*.07:Math.max(1,Math.abs(low)*.05),domain={min:low-pad,max:high+pad};
 const sx=v=>110+(v-domain.min)/(domain.max-domain.min)*580,sy=f=>260-f*220;
 return <svg className="cum-plot" viewBox="0 0 720 335" role="group" aria-label="تجمع تجربی؛ سهم نمره‌های حداکثر آستانه">
 {[0,.25,.5,.75,1].map((f,i)=><g key={i}><line x1="110" x2="690" y1={sy(f)} y2={sy(f)} stroke="#e2e6e5"/><text x="100" y={sy(f)+4} textAnchor="end" direction="ltr">{cumulativePercent(f)}</text></g>)}
 <line x1="110" x2={sx(s.groups[0].value)} y1="260" y2="260" stroke="#28726a" strokeWidth="3"/>
 {s.groups.map((g,i)=><g key={i}><line x1={sx(g.value)} x2={i<s.groups.length-1?sx(s.groups[i+1].value):690} y1={sy(g.fraction)} y2={sy(g.fraction)} stroke="#28726a" strokeWidth="3"/><line x1={sx(g.value)} x2={sx(g.value)} y1={sy(g.before/s.n)} y2={sy(g.fraction)} stroke="#7ba79c" strokeDasharray="3 4"/><circle cx={sx(g.value)} cy={sy(g.before/s.n)} r="4" fill="white" stroke="#28726a" strokeWidth="2"/><circle cx={sx(g.value)} cy={sy(g.fraction)} r={selected===i?8:5} fill={selected===i?'#c58b36':'#28726a'} stroke="white" role="button" tabIndex="0" aria-pressed={selected===i} aria-label={`مقدار ${distributionValue(g.value)}؛ حداکثر ${number(g.cumulative)} از ${number(s.n)}`} onClick={()=>onSelect(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(i);}}}><title>{distributionValue(g.value)+' · '+cumulativePercent(g.fraction)}</title></circle></g>)}
 <line x1={sx(s.threshold)} x2={sx(s.threshold)} y1="40" y2="260" stroke="#c58b36" strokeWidth="2" strokeDasharray="6 5" pointerEvents="none"/><circle cx={sx(s.threshold)} cy={sy(s.inclusive)} r="4" fill="#c58b36" pointerEvents="none"/>
 <line x1="110" x2="690" y1="260" y2="260" stroke="#687783"/>{distributionAxisLabels(domain).map((tick,i)=><text key={i} x={sx(tick.value)} y="285" textAnchor={i===0?'start':i===4?'end':'middle'} direction="ltr">{tick.label}</text>)}<text x="400" y="320" textAnchor="middle">مقدار متغیر کمی</text><text transform="translate(23 153) rotate(-90)" textAnchor="middle">سهم حداکثر</text>
 </svg>;
}
export function CumulativeResults({state,summary:s,dispatch}){
 const selected=s.groups[state.selected];
 return <section className="dist-card cum-results"><h2>از یک نمره به سهم مشاهده‌ها</h2><p>آستانهٔ فعلی: <strong><bdi>{distributionValue(s.threshold)}</bdi></strong>؛ مخرج هر سهم، {number(s.n)} مشاهدهٔ معتبر است.</p><div className="cum-counts"><div><span>کمتر از آستانه</span><strong>{number(s.below)}</strong></div><div><span>برابر آستانه</span><strong>{number(s.equal)}</strong></div><div><span>بیشتر از آستانه</span><strong>{number(s.above)}</strong></div></div><div className="cum-comparisons"><div><h3>کمتر از آستانه</h3><strong>{cumulativePercent(s.strict)}</strong><p>{number(s.below)} ÷ {number(s.n)}؛ برابرها خارج‌اند.</p></div><div className="cum-inclusive"><h3>حداکثر آستانه · تجمع تجربی</h3><strong>{cumulativePercent(s.inclusive)}</strong><p>({number(s.below)} + {number(s.equal)}) ÷ {number(s.n)}؛ همهٔ برابرها داخل‌اند.</p></div><div><h3>رتبه با نصف وزن تساوی</h3><strong>{cumulativePercent(s.midrank)}</strong><p>({number(s.below)} + ۰٫۵ × {number(s.equal)}) ÷ {number(s.n)}؛ قرارداد بخش z.</p></div></div>
 <CumulativePlot summary={s} selected={state.selected} onSelect={index=>dispatch({type:'select',index})}/><p className="small-note">سبز: تجمع تجربی؛ خط طلایی: آستانهٔ فعلی. نقطهٔ توخالی مقدار پیش از پرش و نقطهٔ پُر مقدار در همان نمره را نشان می‌دهد. خط عمودیِ نقطه‌چین فقط محل پرش است. با انتخاب نقطه یا ردیف، آستانه را روی همان مقدار بگذار؛ مقدارهای نزدیک را از جدول انتخاب کن.</p>
 <div className="table-scroll cum-table"><table><caption>تجمع از مقدارهای دقیق، بدون طبقه‌بندی هیستوگرام؛ ردیف‌های برابر گروه‌بندی شده‌اند</caption><thead><tr><th scope="col">مقدار</th><th scope="col">فراوانی</th><th scope="col">تعداد کمتر</th><th scope="col">تعداد حداکثر</th><th scope="col">سهم حداکثر</th></tr></thead><tbody>{s.groups.map((g,i)=><tr key={i} className={state.selected===i?'cum-selected':''}><th scope="row"><button className="text-button" aria-label={'انتخاب مقدار '+distributionValue(g.value)} aria-pressed={state.selected===i} onClick={()=>dispatch({type:'select',index:i})}><bdi>{distributionValue(g.value)}</bdi></button></th><td>{number(g.count)}</td><td>{number(g.before)}</td><td>{number(g.cumulative)}</td><td>{cumulativePercent(g.fraction)}</td></tr>)}</tbody></table></div>
 {selected?<div className="cum-note" role="status"><h3>پرش در مقدار <bdi>{distributionValue(selected.value)}</bdi></h3><p>تجمع از {cumulativePercent(selected.before/s.n)} به {cumulativePercent(selected.fraction)} می‌پرد؛ اندازهٔ پرش {number(selected.count)} ÷ {number(s.n)} = {cumulativePercent(selected.share)} است.</p><p>این مقدار در ردیف‌های اصلی {selected.indices.map(i=>number(i+1)).join('، ')} دیده شده است. همهٔ این مشاهده‌ها در شمارش مانده‌اند.</p></div>:null}
 <section className="cum-quantiles"><h2>از درصد هدف به نمره</h2><p>هدف: <strong>{distributionValue(s.percent)}٪</strong>. دو قرارداد را با همان داده‌ها مقایسه کن.</p><div className="cum-quantile-grid"><div><h3>نوع ۱ · نخستین مقدارِ رسیدن به هدف</h3><strong className="cum-value"><bdi>{distributionValue(s.discrete)}</bdi></strong><p>جایگاه رو به بالا: <bdi dir="ltr">ceil({s.n} × {s.percent} / 100) = {s.position}</bdi>. مقدارِ این جایگاه در داده‌های مرتب انتخاب می‌شود.</p><p>سهم حداکثر این نمره: {cumulativePercent(s.discreteFraction)}؛ با پرش و تساوی‌ها می‌تواند از هدف بیشتر باشد.</p><button className="button secondary compact" onClick={()=>dispatch({type:'useQuantile',method:'discrete'})}>آستانه را روی صدک نوع ۱ بگذار</button></div><div><h3>نوع ۷ · درون‌یابی روی جایگاه‌ها</h3><strong className="cum-value"><bdi>{distributionValue(s.interpolated)}</bdi></strong><p>جایگاه <bdi dir="ltr">h = 1 + ({s.n} − 1) × {s.percent} / 100 ≈ {distributionValue(s.index+1)}</bdi>.</p><p>مقدار جایگاه {number(s.lo+1)}: <bdi>{distributionValue(s.sorted[s.lo])}</bdi>؛ جایگاه {number(s.hi+1)}: <bdi>{distributionValue(s.sorted[s.hi])}</bdi>؛ وزن بین آن‌ها: <bdi>{distributionValue(s.weight)}</bdi>.</p><p>سهم حداکثر این نمره: {cumulativePercent(s.interpolatedFraction)}؛ صدک درون‌یابی‌شده الزاماً مشاهدهٔ خام یا نقطه‌ای با سهم دقیقاً برابر هدف نیست.</p><button className="button secondary compact" onClick={()=>dispatch({type:'useQuantile',method:'interpolated'})}>آستانه را روی صدک نوع ۷ بگذار</button></div></div><p className="small-note">نوع ۷ همان قرارداد چارک‌های ابزارهای کمی این اپ است؛ در صدک ۵۰، میانهٔ معمول دادهٔ کمی را می‌دهد. نوع ۱ همان انتخاب جایگاه تجمعی است و در تعداد زوج ممکن است مقدار میانیِ پایین را برگزیند. این صفحه همهٔ قراردادهای نرم‌افزارها را محاسبه نمی‌کند.</p></section>
 </section>;
}
export function CumulativeWorkspace({state,dispatch,navigate,onDownload}){
 const a=analyzeCumulative(state),p=cumulativePresets[state.preset];
 return <section id="lab-panel" role="tabpanel" aria-labelledby="tab-cumulative"><div className="dist-intro"><h2>چند درصد زیر این نمره‌اند؟ کدام نمره به درصد هدف می‌رسد؟</h2><p>دو جهت را جدا ببین: از نمره به سهم، و از درصد هدف به نمره. در نمره‌های برابر، قرارداد شمارش را روشن کن.</p></div><div className="cum-layout"><aside className="dist-card cum-editor"><h3>داده و سؤال</h3><label htmlFor="cum-preset">مثال ساختگی<select id="cum-preset" value={state.preset} onChange={e=>dispatch({type:'preset',id:e.target.value})}>{Object.entries(cumulativePresets).map(([id,p])=><option key={id} value={id}>{p.label}</option>)}</select></label><p><strong>در نمونهٔ اولیه:</strong> {p.explanation}</p><label htmlFor="cum-data">مقدارهای اصلی<textarea id="cum-data" dir="ltr" rows="4" maxLength="10000" value={state.xtext} aria-invalid={Boolean(a.data.error)} onChange={e=>dispatch({type:'data',field:'xtext',value:e.target.value})}/></label>{a.data.error?<p className="error-message">داده: {a.data.error}</p>:null}<label htmlFor="cum-threshold">آستانهٔ نمره<input id="cum-threshold" type="text" inputMode="decimal" dir="ltr" maxLength="80" value={state.threshold} aria-invalid={Boolean(a.threshold.error)} onChange={e=>dispatch({type:'data',field:'threshold',value:e.target.value})}/></label>{a.threshold.error?<p className="error-message">{a.threshold.error}</p>:null}<label htmlFor="cum-percent">درصد هدف صدک · ۱ تا ۱۰۰<input id="cum-percent" type="text" inputMode="decimal" dir="ltr" maxLength="80" value={state.percent} aria-invalid={Boolean(a.percent.error)} onChange={e=>dispatch({type:'data',field:'percent',value:e.target.value})}/></label>{a.percent.error?<p className="error-message">{a.percent.error}</p>:null}<p className="small-note">۱ تا ۲۰۰ مشاهده و آستانه بین منفی و مثبت یک میلیارد؛ درصد هدف می‌تواند اعشاری باشد. رقم فارسی و نمایش علمی پذیرفته می‌شود. خانهٔ خالی، دادهٔ گمشده یا عدد نامعتبر، صفر فرض نمی‌شود.</p><button className="button secondary" onClick={()=>dispatch({type:'reset'})}>بازنشانی همین مثال</button><p className="small-note">ورودی‌ها و خودسنجی فقط تا هنگام بازبودن این بخش حفظ می‌شوند و جزو پشتیبان یا پیشرفت دوره نیستند. تغییر ورودی انتخاب ردیف را پاک می‌کند؛ انتخاب یا بازنشانی مثال، خودسنجی را هم پاک می‌کند.</p></aside>{a.summary?<CumulativeResults state={state} summary={a.summary} dispatch={dispatch}/>:<section className="dist-card empty-state" role="alert"><h3>ورودی معتبر لازم است</h3><p>{a.error}</p><p>تا اصلاح ورودی، نمودار و نتیجهٔ قبلی نمایش داده نمی‌شوند.</p></section>}</div>
 <section className="dist-card cum-contract"><h2>«زیر» را دقیق بنویس</h2><p>«کمتر از» برابرها را کنار می‌گذارد؛ «حداکثر» آن‌ها را کامل حساب می‌کند. در این صفحه هر دو را می‌بینی. رتبهٔ درصدی با نصف وزن تساوی، قرارداد دیگری است و همان ارتفاع تجمع تجربی نیست. وقتی برابر نداریم، هر سه سهم یکسان می‌شوند.</p><div className="formula" dir="ltr">F(t) = count(X ≤ t) / n<br/>midrank = [count(X &lt; t) + 0.5 × count(X = t)] / n</div><p>پرش در یک مقدار، سهم تکرارهای همان مقدار است. بین دو مقدار مشاهده‌شده، تجمع افقی می‌ماند. این نمودار طبقه‌بندی ندارد و سهم تجربیِ همین فهرست را نشان می‌دهد؛ احتمال جامعه یا نرمال‌بودن را اثبات نمی‌کند.</p><p className="small-note">درصدهای نمایشی گرد می‌شوند؛ مقدارها در جدول و گزارش با دقت Number پذیرفته‌شده نگه داشته می‌شوند. مقایسهٔ آستانه بدون گردکردن و بدون تلورانس مرزی اضافه است؛ نرم‌افزارهای دیگر ممکن است قرارداد یا تلورانس متفاوتی داشته باشند.</p></section>
 <section className="dist-card dist-checks"><h2>خودت را بسنج</h2><p>این سؤال‌ها مثال‌های ثابت دارند؛ پاسخشان با ورودی‌های بالا تغییر نمی‌کند و نتیجه مستقل از پیشرفت دوره است.</p>{cumulativeChecks.map(q=><form key={q.id} onSubmit={e=>{e.preventDefault();dispatch({type:'check',id:q.id});}}><fieldset><legend>{q.question}</legend>{q.options.map((text,value)=><label key={value}><input type="radio" name={'cum-check-'+q.id} checked={state.answers[q.id]===value} onChange={()=>dispatch({type:'answer',id:q.id,value})}/><span>{text}</span></label>)}</fieldset><button className="button secondary compact" type="submit" disabled={!Number.isInteger(state.answers[q.id])||state.checked[q.id]}>بررسی پاسخ</button>{state.checked[q.id]?<p role="status" className={'dist-check-feedback '+(state.answers[q.id]===q.correct?'correct':'retry')}>{q.feedback[state.answers[q.id]]}</p>:null}</form>)}</section>
 <section className="dist-card"><h2>صدک را با روشش گزارش کن</h2><p>صدک یک مقدار روی مقیاس متغیر است؛ رتبهٔ درصدی یک سهم به درصد است. کنار صدک، روش، تعداد مشاهده‌ها و واحد را بنویس. با اختلاف دو خروجی، ابتدا داده‌ها، قرارداد و گردکردن را بررسی کن.</p><div className="dist-actions"><button className="button secondary" disabled={!a.summary} onClick={onDownload}>دریافت گزارش تجمع و صدک</button><button className="text-button" onClick={()=>navigate('lesson',8,{section:'guide-idea'})}>مرور جایگاه نسبی در درس هشتم</button><button className="text-button" onClick={()=>navigate('lab',0,{mode:'z'})}>مقایسه با نمرهٔ z و رتبهٔ درصدی</button><button className="text-button" onClick={()=>navigate('lab',0,{mode:'ordinal'})}>جایگاه تجمعی در دادهٔ ترتیبی</button></div><div className="cum-sources"><a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/ecdf.html" target="_blank" rel="noreferrer">تعریف تجمع تجربی · R</a><a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/quantile.html" target="_blank" rel="noreferrer">قراردادهای صدک · R</a></div></section>
 </section>;
}
export default function Cumulative({navigate=()=>{}}){const [state,dispatch]=useReducer(cumulativeReducer,undefined,initialCumulativeState);function download(){const url=URL.createObjectURL(new Blob(['\uFEFF'+buildCumulativeReport(state)],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='amar-cumulative-quantiles.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}return <CumulativeWorkspace state={state} dispatch={dispatch} navigate={navigate} onDownload={download}/>;}
