import React,{useReducer} from 'react';
import {ArrowLeft,Download,ArrowLeftRight} from 'lucide-react';
import {fmt,number} from './format.js';
import {distributionPresets,distributionChecks,initialDistributionState,distributionReducer,analyzeDistributionInputs,differenceText,buildDistributionReport,distributionValue,distributionAxisLabels} from './distributionComparison.js';

const colors=['#32746b','#a06d26'];
export function DistributionPlot({summary,chart,variable,unit,selected,onSelect}){
 const {min,max}=summary.domain,sx=value=>100+(value-min)/(max-min)*590;
 function point(group,item,y){const active=selected?.group===group.id&&selected.value===item.value,label=`${group.label}، مقدار ${distributionValue(item.value)} ${unit}، ${number(item.count)} مشاهده`;return <g key={item.value}><circle role="button" tabIndex="0" aria-label={label} aria-pressed={active} cx={sx(item.value)} cy={y} r={active?9:6} fill={active?'#d99c2d':colors[group.id]} stroke="white" strokeWidth="2" onClick={()=>onSelect(active?null:{group:group.id,value:item.value})} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();onSelect(active?null:{group:group.id,value:item.value});}}}><title>{label}</title></circle>{item.count>1?<text x={sx(item.value)} y={y-16} textAnchor="middle" className="dist-count">{number(item.count)}</text>:null}</g>;}
 return <figure className="dist-figure"><svg viewBox="0 0 720 350" className="dist-plot" role="group" aria-label={`${chart==='box'?'دو نمودار جعبه‌ای':'نقاط و تکرار مقدارها'} برای ${variable}، واحد ${unit}، با محور مشترک`}><title>دو گروه روی یک محور مشترک؛ اندازهٔ گروه‌ها با n نوشته شده است.</title>{distributionAxisLabels(summary.domain).map(({value,label},i)=><g key={i}><line x1={sx(value)} x2={sx(value)} y1="45" y2="285" className="dist-grid"/><text x={sx(value)} y="307" textAnchor="middle">{label}</text></g>)}{summary.groups.map(group=>{const s=group.stats,y=95+group.id*135;return <g key={group.id}><text x="84" y={y-8} textAnchor="end" className="dist-group-label">{group.label}</text><text x="84" y={y+17} textAnchor="end">n = {number(s.n)}</text>{chart==='box'?<><line x1={sx(s.whiskerLow)} x2={sx(s.whiskerHigh)} y1={y} y2={y} stroke={colors[group.id]} strokeWidth="3"/>{[s.whiskerLow,s.whiskerHigh].map((value,index)=><line key={index} x1={sx(value)} x2={sx(value)} y1={y-13} y2={y+13} stroke={colors[group.id]} strokeWidth="3"/>)}<rect x={sx(s.q1)} y={y-25} width={sx(s.q3)-sx(s.q1)} height="50" fill={group.id===0?'#dfede7':'#f5e8cd'} stroke={colors[group.id]} strokeWidth="2"/><line x1={sx(s.median)} x2={sx(s.median)} y1={y-25} y2={y+25} stroke="#173d32" strokeWidth="4"/>{group.frequencies.filter(item=>s.outliers.includes(item.value)).map(item=>point(group,item,y))}</>:<><line x1="100" x2="690" y1={y} y2={y} className="dist-lane"/>{group.frequencies.map(item=>point(group,item,y))}<line x1={sx(s.median)} x2={sx(s.median)} y1={y+17} y2={y+43} stroke="#173d32" strokeWidth="3"/></>}<polygon points={`${sx(s.mean)},${y+30} ${sx(s.mean)+7},${y+37} ${sx(s.mean)},${y+44} ${sx(s.mean)-7},${y+37}`} fill="#d99c2d"><title>{`میانگین ${group.label}: ${fmt(s.mean)} ${unit}`}</title></polygon></g>;})}<line x1="100" x2="690" y1="286" y2="286" className="dist-lane"/><text x="395" y="339" textAnchor="middle">{variable} ({unit})</text></svg><div className="dist-legend"><span><i className="dist-median"/>میانه: خط تیره</span><span><i className="dist-mean"/>میانگین: لوزی طلایی</span></div><figcaption>{chart==='box'?'جعبه از Q1 تا Q3 است؛ سبیل‌ها تا آخرین مقدار داخل کرانه‌های ۱٫۵ IQR می‌روند. نقطه‌های بیرون، مقدارهای علامت‌خورده‌اند و حذف نشده‌اند. ضخامت جعبه‌ها یکسان است و تعداد را نشان نمی‌دهد.':'هر نقطه یک مقدار متمایز است؛ عدد بالای آن تعداد تکرارهاست و نقطهٔ بدون عدد یک مشاهده دارد. تعدادها درصد نیستند؛ برای سهم هر مقدار، جدول را ببین.'} هر دو گروه دقیقاً یک مقیاس عددی دارند. روی نقطه‌ها کلیک کن یا با Tab و Enter آن‌ها را انتخاب کن.</figcaption></figure>;
}
export function DistributionResults({summary,state,dispatch}){
 const variable=state.variable.trim()||'متغیر مشخص‌نشده',unit=state.unit.trim()||'واحد مشخص‌نشده',selected=state.selected,item=selected?summary.groups[selected.group].frequencies.find(row=>row.value===selected.value):null;
 const fields=[['n','تعداد معتبر',false],['mean','میانگین',true],['median','میانه',true],['sd','انحراف معیار نمونه‌ای',true],['q1','چارک اول',true],['q3','چارک سوم',true],['iqr','IQR',true],['min','کمترین مقدار',true],['max','بیشترین مقدار',true]];
 return <div className="dist-output"><section className="dist-card"><div className="dist-output-heading"><h2>دو گروه، یک مقیاس</h2><label htmlFor="dist-chart">نمایش<select id="dist-chart" value={state.chart} onChange={event=>dispatch({type:'chart',value:event.target.value})}><option value="box">جعبه‌ای: مرکز و پراکندگی</option><option value="dots">نقاط و تعداد تکرارها</option></select></label></div><DistributionPlot summary={summary} chart={state.chart} variable={variable} unit={unit} selected={selected} onSelect={value=>dispatch({type:'select',value})}/><p className="dist-selection" role="status">{item?`${summary.groups[selected.group].label} · مقدار ${distributionValue(item.value)} ${unit} · ${number(item.count)} مشاهده از ${number(summary.groups[selected.group].stats.n)} · سهم ${fmt(100*item.count/summary.groups[selected.group].stats.n)}٪`:'یک مقدار را در نمودار نقطه‌ای یا جدول تکرارها انتخاب کن؛ تعداد و سهم آن در همان گروه نمایش داده می‌شود.'}</p></section>
  <section className="dist-card"><h2>مرکز، پراکندگی و تعداد را کنار هم بخوان</h2><div className="table-scroll" role="region" tabIndex="0" aria-label="خلاصه‌های عددی دو گروه"><table className="dist-table"><caption>{variable} · واحد مشترک: {unit} · تعداد، واحد اندازه‌گیری ندارد</caption><thead><tr><th scope="col">شاخص</th>{summary.groups.map(group=><th scope="col" key={group.id}>{group.label}</th>)}</tr></thead><tbody>{fields.map(([key,label,hasUnit])=><tr key={key}><th scope="row">{label}{hasUnit?<small>{unit}</small>:null}</th>{summary.groups.map(group=><td key={group.id}>{key==='n'?number(group.stats.n):fmt(group.stats[key])}</td>)}</tr>)}<tr><th scope="row">تعداد مقدارهای علامت‌خورده</th>{summary.groups.map(group=><td key={group.id}>{number(group.stats.outliers.length)}</td>)}</tr></tbody></table></div><div className="dist-difference"><strong>میانگین ب منهای میانگین الف</strong><span>{differenceText(summary.meanDifference)} <small>{unit}</small></span><p>{summary.meanDifference===0?'میانگین‌ها در این داده برابرند؛ برای مقایسهٔ پراکندگی، انحراف معیار و IQR را هم ببین.':`میانگین گروه ب در این داده ${summary.meanDifference>0?'بالاتر':'پایین‌تر'} است. این تفاوت دربارهٔ همهٔ افراد یا علت تفاوت نتیجهٔ قطعی نمی‌دهد.`}</p></div><p className="small-note">محاسبات با مقدارهای اصلی انجام می‌شوند؛ نمایش خلاصه‌ها تا دو رقم اعشار گرد شده است؛ جدول مقدارها دقت اصلی را نگه می‌دارد و برچسب محور متناسب با فاصلهٔ مقدارها نمایش داده می‌شود. انحراف معیار با n−1 و چارک‌ها با روش نوع ۷ محاسبه می‌شوند. برای گروه تک‌مشاهده‌ای، انحراف معیار نمونه‌ای تعریف‌نشده است؛ جعبه نیز به یک مقدار فرو می‌ریزد.</p><p className="small-note">IQR صفر یا جعبهٔ کوتاه، به معنی برابر بودن همهٔ مقدارها نیست؛ مقدارهای بیرون جعبه و نقاط را هم بررسی کن.</p></section>
  <details className="dist-card dist-frequencies"><summary>مقدارها، تکرارها و مخرج درصد را بازبینی کن</summary>{summary.groups.map(group=><div key={group.id} className="table-scroll" role="region" tabIndex="0" aria-label={'جدول تکرار '+group.label}><table className="dist-table"><caption>{group.label} · مخرج هر درصد: {number(group.stats.n)} مشاهدهٔ همان گروه</caption><thead><tr><th scope="col">مقدار ({unit})</th><th scope="col">تعداد</th><th scope="col">درصد در گروه</th></tr></thead><tbody>{group.frequencies.map(row=><tr key={row.value} className={selected?.group===group.id&&selected.value===row.value?'dist-selected-row':''}><th scope="row"><button className="dist-value-button" aria-pressed={selected?.group===group.id&&selected.value===row.value} aria-label={`${group.label}، مقدار ${distributionValue(row.value)} ${unit}`} onClick={()=>dispatch({type:'select',value:selected?.group===group.id&&selected.value===row.value?null:{group:group.id,value:row.value}})}><bdi dir="ltr">{distributionValue(row.value)}</bdi></button></th><td>{number(row.count)}</td><td>{fmt(100*row.count/group.stats.n)}٪</td></tr>)}</tbody></table></div>)}<p className="small-note">جمع درصدهای نمایشی ممکن است به دلیل گردکردن دقیقاً ۱۰۰ نشود. دو فهرست جدا هستند؛ ردیف الف و ب، یک جفت مشاهده تلقی نمی‌شوند.</p></details></div>;
}
export function DistributionWorkspace({state,dispatch,onDownload,navigate}){
 const {parsed,summary}=analyzeDistributionInputs(state.texts);
 return <section id="lab-panel" role="tabpanel" aria-labelledby="tab-distributions" className="dist-lab"><header className="dist-opening"><span className="dist-kicker">یک متغیر کمی در دو گروه</span><h2>میانگین برابر، داستان برابر؟</h2><p>دو گروه را با مرکز، پراکندگی، تعداد و مقدارهای واقعی‌شان مقایسه کن. ابتدا مطمئن شو هر دو فهرست، یک متغیر را با واحد و روش اندازه‌گیری قابل مقایسه نشان می‌دهند.</p></header><div className="dist-presets" aria-label="مثال‌های ساختگی">{Object.entries(distributionPresets).map(([id,preset])=><button className="button secondary" key={id} aria-pressed={state.preset===id} onClick={()=>dispatch({type:'preset',value:id})}>{preset.label}</button>)}</div>{state.preset!=='custom'?<aside className="dist-story"><strong>در این مثال چه چیزی تغییر کرده؟</strong><p>{distributionPresets[state.preset].lesson}</p></aside>:null}<div className="dist-workspace"><aside className="dist-card dist-editor"><h2>داده‌های هر گروه</h2><label htmlFor="dist-variable">نام متغیر<input id="dist-variable" maxLength={60} value={state.variable} onChange={event=>dispatch({type:'metadata',id:'variable',value:event.target.value})}/></label><label htmlFor="dist-unit">واحد مشترک<input id="dist-unit" maxLength={60} value={state.unit} onChange={event=>dispatch({type:'metadata',id:'unit',value:event.target.value})}/></label>{['الف','ب'].map((label,index)=><div key={label}><label htmlFor={'dist-data-'+index}>گروه {label}<textarea id={'dist-data-'+index} value={state.texts[index]} rows={4} maxLength={8000} aria-invalid={Boolean(parsed[index].error)} aria-describedby={'dist-data-help'+(parsed[index].error?' dist-error-'+index:'')} onChange={event=>dispatch({type:'data',group:index,value:event.target.value})}/></label>{parsed[index].error?<p id={'dist-error-'+index} className="error-message" role="alert">{parsed[index].error}</p>:<small>{number(parsed[index].values.length)} مشاهدهٔ معتبر</small>}</div>)}<p className="small-note" id="dist-data-help">هر گروه مستقل است و اندازه‌ها می‌توانند متفاوت باشند. تا ۲۰۰ مقدار در هر گروه؛ بین منفی و مثبت یک میلیارد. ارقام فارسی و عربی، اعشار و مقدار صفر پذیرفته می‌شوند. عددها را با فاصله، ویرگول یا سطر جدید جدا کن؛ مقدار گمشده را صفر فرض نکن.</p><button className="button secondary" onClick={()=>dispatch({type:'swap'})}><ArrowLeftRight size={18}/>جابجایی فهرست الف و ب</button><p className="small-note">نمونه‌های آماده ساختگی‌اند. ورودی‌ها و خودسنجی فقط تا هنگام بازبودن این بخش حفظ می‌شوند و جزو پشتیبان پیشرفت نیستند.</p></aside>{summary?<DistributionResults summary={summary} state={state} dispatch={dispatch}/>:<section className="dist-card empty-state"><h2>هر دو فهرست را کامل و معتبر کن</h2><p>تا اصلاح ورودی، مقایسه و نمودار نمایش داده نمی‌شوند؛ عددهای قبلی به‌جای دادهٔ نامعتبر باقی نمی‌مانند.</p></section>}</div>
  <section className="dist-card dist-checks"><h2>خودت را بسنج</h2><p>این دو سؤال دربارهٔ مثال ثابت و روش تفسیرند؛ با تغییر فهرست‌های بالا، سؤال‌ها تغییر نمی‌کنند. پاسخ‌ها فقط در همین بخش نگهداری می‌شوند.</p>{distributionChecks.map(question=><form key={question.id} onSubmit={event=>{event.preventDefault();dispatch({type:'check',id:question.id});}}><fieldset><legend>{question.question}</legend>{question.options.map((option,index)=><label key={option}><input type="radio" name={'dist-check-'+question.id} checked={state.answers[question.id]===index} onChange={()=>dispatch({type:'answer',id:question.id,value:index})}/><span>{option}</span></label>)}</fieldset><button className="button secondary compact" disabled={!Number.isInteger(state.answers[question.id])||state.checked[question.id]} type="submit">بررسی پاسخ</button>{state.checked[question.id]?<p className={'dist-check-feedback '+(state.answers[question.id]===question.correct?'correct':'retry')} role="status">{question.feedback[state.answers[question.id]]}</p>:null}</form>)}</section><section className="dist-card dist-limits"><h2>نتیجه را تا کجا می‌توان گفت؟</h2><p>مرکز و پراکندگیِ همین داده را توصیف کن. تفاوت دو گروه به‌تنهایی نشان نمی‌دهد عضویت در گروه علت تغییر نمره است یا تفاوت در جامعه قطعی است. این ابزار آزمون فرض و فاصلهٔ اطمینان انجام نمی‌دهد.</p><p>علامت دورافتادگی به معنی نامعتبر بودن مقدار نیست. منبع، واحد و علت ثبت را بررسی کن؛ ابزار هیچ مقداری را خودکار حذف نمی‌کند. برای دادهٔ اسمی یا ترتیبی، میانگین کدهای دلخواه دسته‌ها جای این تحلیل را نمی‌گیرد.</p><div className="dist-actions"><button className="button secondary" onClick={onDownload}><Download size={18}/>دریافت گزارش مقایسه</button><button className="text-button" onClick={()=>navigate('lesson',5,{section:'guide-idea'})}>مرور مرکز و پراکندگی<ArrowLeft size={18}/></button></div><a className="guide-source" href="https://www.itl.nist.gov/div898/handbook/eda/section3/boxplot.htm" target="_blank" rel="noreferrer">برای مطالعهٔ بیشتر: مقایسهٔ گروه‌ها با نمودار جعبه‌ای · NIST</a></section></section>;
}
export default function DistributionComparison({navigate=()=>{}}){
 const [state,dispatch]=useReducer(distributionReducer,undefined,initialDistributionState);
 function download(){const url=URL.createObjectURL(new Blob(['\uFEFF'+buildDistributionReport(state)],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='amar-group-distributions.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <DistributionWorkspace state={state} dispatch={dispatch} onDownload={download} navigate={navigate}/>;
}
