import {test} from 'node:test';
import assert from 'node:assert/strict';
import {distributionPresets,distributionChecks,valueFrequencies,distributionValue,distributionAxisLabels,compareDistributions,analyzeDistributionInputs,initialDistributionState,distributionReducer,differenceText,buildDistributionReport} from './distributionComparison.js';
const near=(actual,expected)=>assert.ok(Math.abs(actual-expected)<1e-10,`${actual} != ${expected}`);
const act=(state,type,other={})=>distributionReducer(state,{type,...other});
test('equal means can retain unequal sample SD and type seven IQR',()=>{const result=compareDistributions(distributionPresets.spread.groups),[a,b]=result.groups.map(group=>group.stats);assert.equal(a.mean,7);assert.equal(b.mean,7);assert.equal(a.median,7);assert.equal(b.median,7);near(a.sd,Math.sqrt(2/3));near(b.sd,Math.sqrt(58/3));assert.equal(a.iqr,.5);assert.equal(b.iqr,5.5);assert.equal(result.meanDifference,0);assert.ok(result.domain.min<=2&&result.domain.max>=12);});
test('adding a constant shifts centers while preserving spread and relative fences',()=>{const result=compareDistributions(distributionPresets.shift.groups),[a,b]=result.groups.map(group=>group.stats);assert.equal(result.meanDifference,4);assert.equal(result.medianDifference,4);near(a.sd,b.sd);assert.equal(a.iqr,b.iqr);assert.equal(b.q1-a.q1,4);assert.equal(b.lower-a.lower,4);});
test('unequal groups have independent n and within-group percentages',()=>{const result=compareDistributions(distributionPresets.unequal.groups),[a,b]=result.groups;assert.equal(a.stats.n,4);assert.equal(b.stats.n,12);assert.equal(result.meanDifference,0);assert.equal(a.stats.median,b.stats.median);for(const group of [a,b]){assert.equal(group.frequencies.reduce((sum,row)=>sum+row.count,0),group.stats.n);near(group.frequencies.reduce((sum,row)=>sum+100*row.count/group.stats.n,0),100);}assert.equal(a.frequencies[1].count,2);assert.equal(b.frequencies[1].count,6);near(a.stats.sd,Math.sqrt(2/3));near(b.stats.sd,Math.sqrt(6/11));});
test('flagged outlier remains in every calculation and original data',()=>{const before=JSON.stringify(distributionPresets.outlier.groups),result=compareDistributions(distributionPresets.outlier.groups),[a,b]=result.groups;assert.equal(a.stats.mean,6);assert.equal(b.stats.mean,8.75);assert.equal(a.stats.median,b.stats.median);assert.equal(a.stats.iqr,b.stats.iqr);assert.deepEqual(b.stats.outliers,[30]);assert.equal(b.stats.n,8);assert.equal(b.values.at(-1),30);assert.equal(JSON.stringify(distributionPresets.outlier.groups),before);});
test('real zero, constant data and one-observation groups keep explicit undefined sample SD',()=>{for(const values of [[[0],[0]],[[7,7,7],[7,7]]]){const result=compareDistributions(values);assert.ok(result);assert.ok(result.domain.max>result.domain.min);assert.equal(result.groups[0].stats.iqr,0);}const single=compareDistributions([[0],[1,2]]);assert.equal(single.groups[0].stats.sd,null);assert.equal(single.sdDifference,null);assert.equal(compareDistributions([[7,7],[7,7]]).groups[0].stats.sd,0);});
test('both groups must be complete and finite, without forcing equal sample sizes',()=>{assert.equal(analyzeDistributionInputs(['۵، ۶، ۷٫۵، −۲','١ ٢ ٠']).summary.groups[1].stats.n,3);for(const invalid of ['', '2,,4','NaN','Infinity','1000000001'])assert.equal(analyzeDistributionInputs([invalid,'1 2 3']).summary,null,invalid);for(const values of [[],[[1],[]],[[1],[NaN]],[[1],[Infinity]],[[1],[1e9+1]],[[1],Array(201).fill(3)]])assert.equal(compareDistributions(values),null);assert.ok(compareDistributions([[1e9],Array(200).fill(-1e9)]));assert.equal(analyzeDistributionInputs(['1',Array(201).fill(2).join(',')]).summary,null);});
test('frequency display groups repeated values without discarding any observations',()=>{assert.deepEqual(valueFrequencies([3,0,3,-2,0,3]),[{value:-2,count:1},{value:0,count:2},{value:3,count:3}]);assert.equal(compareDistributions([Array(200).fill(0),[1]]).groups[0].frequencies[0].count,200);});
test('swapping groups reverses signed mean difference and clears stale selection',()=>{let state=act(initialDistributionState(),'preset',{value:'shift'});state=act(state,'select',{value:{group:0,value:4}});assert.ok(state.selected);const original=analyzeDistributionInputs(state.texts).summary.meanDifference;state=act(state,'swap');assert.equal(state.selected,null);assert.equal(analyzeDistributionInputs(state.texts).summary.meanDifference,-original);state=act(state,'data',{group:0,value:'bad'});assert.equal(analyzeDistributionInputs(state.texts).summary,null);assert.equal(state.preset,'custom');});
test('fixed interpretation questions provide specific feedback and do not change with input data',()=>{let state=initialDistributionState();for(const q of distributionChecks){assert.equal(q.options.length,q.feedback.length);assert.equal(act(state,'check',{id:q.id}),state);for(let i=0;i<q.options.length;i++){state=act(state,'answer',{id:q.id,value:i});assert.equal(state.checked[q.id],false);state=act(state,'check',{id:q.id});assert.equal(state.checked[q.id],true);assert.ok(q.feedback[i].length>20);}state=act(state,'answer',{id:q.id,value:q.correct});state=act(state,'check',{id:q.id});}const answers={...state.answers},checked={...state.checked};state=act(state,'preset',{value:'outlier'});assert.deepEqual(state.answers,answers);assert.deepEqual(state.checked,checked);});
test('reports preserve full decimal precision and original order without inventing results for invalid input',()=>{let state=act(initialDistributionState(),'data',{group:0,value:'1.1234567, 0, -2'});state=act(state,'data',{group:1,value:'10, 8'});state=act(state,'metadata',{id:'unit',value:'ثانیه'});const text=buildDistributionReport(state);assert.ok(text.includes('الف,1,1.1234567\nالف,2,0\nالف,3,-2\nب,1,10\nب,2,8'));assert.match(text,/ورودی کاربر/);assert.match(text,/ثانیه/);assert.match(text,/جفت‌سازی نمی‌شوند/);assert.match(text,/n−1/);const invalid=buildDistributionReport(act(state,'data',{group:1,value:''}));assert.match(invalid,/محاسبه انجام نشده/);assert.doesNotMatch(invalid,/تفاوت میانگین،/);const one=buildDistributionReport(act(state,'data',{group:0,value:'0'}));assert.match(one,/انحراف معیار نمونه‌ای تعریف‌نشده/);});
test('tiny differences are not described as exact zero, and invalid actions retain state',()=>{assert.equal(differenceText(0),'۰');assert.match(differenceText(.0001),/مثبت/);assert.match(differenceText(-.0001),/منفی/);assert.match(differenceText(.0001),/کمتر از/);assert.equal(differenceText(null),'تعریف‌نشده');const state=initialDistributionState();for(const action of [{type:'preset',value:'__proto__'},{type:'data',group:2,value:'1'},{type:'data',group:0,value:'1'.repeat(8001)},{type:'metadata',id:'unit',value:'a'.repeat(61)},{type:'select',value:{group:0,value:123}},{type:'chart',value:'pie'},{type:'answer',id:'center',value:10},{type:'check',id:'unknown'}])assert.equal(distributionReducer(state,action),state);});

test('raw-value labels and shared-axis ticks distinguish close and very small observations',()=>{assert.equal(distributionValue(.0001),'۰٫۰۰۰۱');assert.equal(distributionValue(1.1234567),'۱٫۱۲۳۴۵۶۷');for(const groups of [[[0],[.0001]],[[1e-25],[2e-25]],[[1e9],[1e9-.01]]]){const labels=distributionAxisLabels(compareDistributions(groups).domain).map(tick=>tick.label);assert.equal(new Set(labels).size,5);}});
