import React,{useState} from 'react';
import {fmt,number} from './format.js';
import {groupPresets,percentBases,summarizeGroups,percentageCell,parseCount} from './groupComparison.js';
const groups=['گروه الف','گروه ب'],responses=['پاسخ مثبت','پاسخ منفی'];
const percent=value=>value===null?'تعریف‌نشده':fmt(value)+'٪';
export function GroupResults({summary,basis,chartMode,selected,onSelect}){
  const cell=percentageCell(summary,...selected,basis),max=chartMode==='rate'?100:Math.max(1,...summary.cells.map(row=>row[0]));
  const gap=summary.difference===null?null:Math.abs(summary.difference)<0.01?'کمتر از ۰٫۰۱':fmt(Math.abs(summary.difference));
  return <>
    <section className="group-card"><h2>جدول دوطرفه: گروه × پاسخ</h2><p>هر فرد در یک گروه و یکی از دو پاسخ قرار دارد. کنار تعداد هر خانه، درصد با مخرج انتخاب‌شده دیده می‌شود.</p><div className="table-scroll"><table className="group-table"><caption>{percentBases[basis].label} · مجموع‌ها تعداد هستند</caption><thead><tr><th scope="col">گروه</th>{responses.map(label=><th scope="col" key={label}>{label}</th>)}<th scope="col">مجموع گروه</th></tr></thead><tbody>{summary.cells.map((row,r)=><tr key={r}><th scope="row">{groups[r]}</th>{row.map((count,c)=><td key={c}><button className={'group-cell '+(selected[0]===r&&selected[1]===c?'selected':'')} aria-pressed={selected[0]===r&&selected[1]===c} aria-label={`${groups[r]}، ${responses[c]}، تعداد ${number(count)}، ${percent(percentageCell(summary,r,c,basis).value)}`} onClick={()=>onSelect([r,c])}><strong>{number(count)}</strong><small>{percent(percentageCell(summary,r,c,basis).value)}</small></button></td>)}<td>{number(summary.rows[r])}</td></tr>)}</tbody><tfoot><tr><th scope="row">مجموع پاسخ</th>{summary.columns.map((n,i)=><td key={i}>{number(n)}</td>)}<td>{number(summary.total)}</td></tr></tfoot></table></div><p className="small-note">{percentBases[basis].help} مجموع‌ها از درصدهای گرد‌شده محاسبه نمی‌شوند.</p>
      <div className="group-denominator" aria-live="polite"><span>{groups[selected[0]]} · {responses[selected[1]]}</span><strong>{cell.value===null?'مخرج صفر است؛ درصد تعریف نمی‌شود.':`${number(cell.numerator)} ÷ ${number(cell.denominator)} × ۱۰۰ = ${percent(cell.value)}`}</strong><p>{basis==='row'?`از ${number(cell.denominator)} نفرِ ${groups[selected[0]]}، ${number(cell.numerator)} نفر ${responses[selected[1]]} داده‌اند.`:basis==='column'?`از ${number(cell.denominator)} نفر با ${responses[selected[1]]}، ${number(cell.numerator)} نفر در ${groups[selected[0]]} هستند.`:`از کل ${number(cell.denominator)} نفر، ${number(cell.numerator)} نفر هم در ${groups[selected[0]]} هستند و هم ${responses[selected[1]]} داده‌اند.`}</p></div>
    </section>
    <section className="group-card"><h2>{chartMode==='rate'?'در هر گروه چند درصد پاسخ مثبت داده‌اند؟':'در هر گروه چند نفر پاسخ مثبت داده‌اند؟'}</h2><p className="small-note">{chartMode==='rate'?'مقیاس مشترک از صفر تا ۱۰۰٪؛ مخرج هر میله اندازهٔ همان گروه است.':'هر دو میله از صفر و با مقیاس یکسان رسم شده‌اند؛ طول میله تعداد پاسخ مثبت را نشان می‌دهد.'}</p><div className="group-bars" role="img" aria-label={summary.cells.map((row,r)=>`${groups[r]}: ${chartMode==='rate'?percent(summary.rates[r]):number(row[0])+' نفر'}؛ اندازهٔ گروه ${number(summary.rows[r])}`).join('؛ ')}>{summary.cells.map((row,r)=>{const value=chartMode==='rate'?summary.rates[r]:row[0];return <div className="group-bar-row" key={r}><span>{groups[r]}<small>n = {number(summary.rows[r])}</small></span><div className="group-bar-track"><div className={'group-bar group-bar-'+r} style={{width:(value===null?0:100*value/max)+'%'}}/></div><strong>{chartMode==='rate'?percent(value):number(value)+' نفر'}</strong></div>;})}</div><p className="insight">{summary.difference===null?'یک گروه مشاهده ندارد؛ مقایسهٔ درصد پاسخ مثبت دو گروه تعریف نمی‌شود.':summary.difference===0?'درصد پاسخ مثبت در دو گروه برابر است؛ تعدادهای خام ممکن است برابر نباشند.':`درصد پاسخ مثبت در ${summary.difference>0?'گروه الف':'گروه ب'}، ${gap} واحد درصد بیشتر است.`}</p><p>برای پرسش «در هر گروه چه سهمی پاسخ مثبت دارد؟»، درصد سطری را مقایسه کن و اندازهٔ هر گروه را نیز گزارش کن. تفاوت درصدها به‌تنهایی علت تفاوت یا نتیجهٔ کل جامعه را اثبات نمی‌کند.</p><p className="small-note">«واحد درصد» تفاضل دو درصد است؛ مثلاً ۸۰٪ منهای ۴۰٪ برابر ۴۰ واحد درصد است.</p></section>
  </>;
}
export default function GroupComparison(){
  const [cells,setCells]=useState([...groupPresets.unequal.cells]),[preset,setPreset]=useState('unequal'),[basis,setBasis]=useState('row'),[chartMode,setChartMode]=useState('count'),[selected,setSelected]=useState([0,0]),[answer,setAnswer]=useState(null);
  const summary=summarizeGroups(cells);
  return <section id="lab-panel" role="tabpanel" aria-labelledby="tab-groups" className="group-lab">
    <header className="group-opening"><span className="eyebrow">اول تعداد، بعد مخرج</span><h2>بزرگ‌تر بودن گروه، سهم بیشتر را تضمین نمی‌کند.</h2><p>در نمونهٔ اول این نظرسنجی ساختگی، ۸ نفر از ۱۰ نفرِ گروه الف و ۱۲ نفر از ۳۰ نفرِ گروه ب پاسخ مثبت داده‌اند. گروه ب پاسخ مثبت بیشتری دارد؛ اما سهم پاسخ مثبت در گروه الف بیشتر است. نمایش نمودار را به «درصد درون گروه» تغییر بده و تفاوت را ببین.</p><p className="small-note">این ابزار جدول ۲ × ۲ برای دو متغیر دسته‌ای است. فقط تعداد پاسخ‌های معتبر وارد می‌شود؛ پاسخ گمشده را منفی یا صفر فرض نکن.</p></header>
    <div className="group-workspace"><aside className="group-card group-editor"><h2>آزمایش کن</h2><label>نمونهٔ آماده<select value={preset} onChange={e=>{setPreset(e.target.value);setCells([...groupPresets[e.target.value].cells]);setSelected([0,0]);}}><option value="custom" disabled>داده‌های تغییرکردهٔ شما</option>{Object.entries(groupPresets).map(([id,p])=><option key={id} value={id}>{p.label}</option>)}</select></label>{groups.map((label,r)=><fieldset key={r}><legend>{label}</legend>{responses.map((response,c)=><label key={c}>{response}<input type="text" inputMode="numeric" value={cells[r*2+c]} aria-invalid={parseCount(cells[r*2+c])===null} aria-describedby="group-input-help" onChange={e=>{setPreset('custom');setCells(current=>current.map((value,i)=>i===r*2+c?e.target.value:value));}}/></label>)}</fieldset>)}<p id="group-input-help" className="small-note">تعدادها باید عدد صحیح بین صفر و ۱٬۰۰۰٬۰۰۰ باشند. ارقام فارسی و عربی پذیرفته می‌شوند. ورودی خالی به معنی صفر نیست.</p>{!summary?<p className="error-message" role="alert">هر چهار تعداد را کامل و معتبر وارد کن؛ درصدهای قبلی تا اصلاح ورودی نمایش داده نمی‌شوند.</p>:null}<label>مخرج درصدهای جدول<select value={basis} onChange={e=>setBasis(e.target.value)}>{Object.entries(percentBases).map(([id,b])=><option key={id} value={id}>{b.label}</option>)}</select></label><label>نمایش نمودار پاسخ مثبت<select value={chartMode} onChange={e=>setChartMode(e.target.value)}><option value="count">تعداد خام</option><option value="rate">درصد درون گروه</option></select></label><p className="small-note">مخرجِ جدول و نمایش نمودار جدا انتخاب می‌شوند. نمودار درصدی همیشه درصد درون هر گروه را مقایسه می‌کند.</p></aside><div className="group-output">{summary?<GroupResults summary={summary} basis={basis} chartMode={chartMode} selected={selected} onSelect={setSelected}/>:<div className="empty-state"><h2>منتظر تعدادهای معتبر</h2><p>هیچ مقدار ناقص یا نامعتبری وارد محاسبه نمی‌شود.</p></div>}</div></div>
    <section className="group-card group-check"><h2>مخرج درست را انتخاب کن</h2><p>«از کسانی که پاسخ مثبت داده‌اند، چند درصد در گروه الف هستند؟» تعداد پاسخ مثبت گروه الف را باید بر چه چیزی تقسیم کنیم؟</p><div className="group-answer-options">{[['row','کل افراد گروه الف'],['column','کل پاسخ‌های مثبت در هر دو گروه'],['total','کل افراد هر دو گروه']].map(([id,label])=><button className="button secondary" key={id} aria-pressed={answer===id} onClick={()=>setAnswer(id)}>{label}</button>)}</div>{answer?<p role="status" className="insight">{answer==='column'?'درست است: سؤال ابتدا همهٔ پاسخ‌های مثبت را انتخاب کرده؛ مخرج، مجموع ستون پاسخ مثبت است.':answer==='row'?'این مخرج جوابِ سؤال دیگری است: «در گروه الف چند درصد پاسخ مثبت داده‌اند؟» در سؤال فعلی، کل پاسخ‌های مثبت را مخرج قرار بده.':'کل نمونه، سهم خانه از همهٔ افراد را نشان می‌دهد. سؤال فعلی فقط دربارهٔ کسانی است که پاسخ مثبت داده‌اند؛ مخرج، کل پاسخ‌های مثبت است.'}</p>:null}<a className="guide-source" href="https://openstax.org/books/introductory-statistics-2e/pages/3-4-contingency-tables" target="_blank" rel="noopener noreferrer">برای مطالعهٔ بیشتر: جدول دوطرفه · OpenStax</a></section>
  </section>;
}
