import React,{useReducer} from 'react';
import {binPresets,binChecks,initialBinState,binReducer,analyzeBins,binInterval,binHeight,buildBinReport} from './histogramBins.js';
import {distributionValue,distributionAxisLabels} from './distributionComparison.js';
import {fmt,number} from './format.js';

export function BinPlot({summary,chart,selected,onSelect}){
 const count=chart==='count',heights=summary.bins.map(b=>count?b.count:b.density),peak=Math.max(...heights);
 const span=summary.edges.at(-1)-summary.edges[0],sx=value=>110+(value-summary.edges[0])/span*580,sy=value=>250-value/peak*210;
 return <svg className="bins-plot" viewBox="0 0 720 335" role="group" aria-label={count?'هیستوگرام تعداد با طبقه‌های هم‌عرض':'هیستوگرام چگالی؛ مساحت هر طبقه سهم آن است'}>
  {[0,.25,.5,.75,1].map((fraction,i)=><g key={i}><line x1="110" x2="690" y1={250-fraction*210} y2={250-fraction*210} stroke="#e2e6e5"/><text x="100" y={254-fraction*210} textAnchor="end" direction="ltr">{binHeight(peak*fraction)}</text></g>)}
  {summary.bins.map((b,i)=><rect key={i} x={sx(b.lo)} y={sy(heights[i])} width={(b.width/span)*580} height={heights[i]/peak*210} fill={selected===i?'#c58b36':'#28726a'} fillOpacity=".8" stroke="white" strokeWidth="1" role="button" tabIndex="0" aria-pressed={selected===i} aria-label={`طبقهٔ ${number(i+1)}؛ ${binInterval(b)}؛ تعداد ${number(b.count)}؛ سهم ${fmt(b.share*100)} درصد`} onClick={()=>onSelect(selected===i?null:i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(selected===i?null:i);}}}><title>{binInterval(b)+' · '+number(b.count)+' مشاهده'}</title></rect>)}
  <line x1="110" x2="690" y1="250" y2="250" stroke="#687783"/>{distributionAxisLabels({min:summary.edges[0],max:summary.edges.at(-1)}).map((tick,i)=><text key={i} x={sx(tick.value)} y="277" textAnchor={i===0?'start':i===4?'end':'middle'} direction="ltr">{tick.label}</text>)}
  <text x="400" y="316" textAnchor="middle">مقدار متغیر کمی</text><text transform="translate(22 147) rotate(-90)" textAnchor="middle">{count?'تعداد':'چگالی'}</text>
 </svg>;
}
export function BinResults({state,summary:s,dispatch}){
 const chart=state.chart==='count'&&s.equalWidth?'count':'density',selected=s.bins[state.selected];
 return <section className="dist-card bins-results"><h2>از مشاهده تا مساحت طبقه</h2><div className="metric-strip"><div><span>تعداد دادهٔ اصلی</span><strong>{number(s.n)}</strong></div><div><span>میانگین دادهٔ اصلی</span><strong>{binHeight(s.mean)}</strong></div><div><span>میانهٔ دادهٔ اصلی</span><strong>{binHeight(s.median)}</strong></div></div>
 <fieldset className="bins-chart-choice"><legend>معنای ارتفاع میله</legend><label><input type="radio" name="bins-chart" checked={chart==='density'} onChange={()=>dispatch({type:'chart',value:'density'})}/>چگالی؛ سهم از مساحت خوانده می‌شود</label><label><input type="radio" name="bins-chart" checked={chart==='count'} disabled={!s.equalWidth} onChange={()=>dispatch({type:'chart',value:'count'})}/>تعداد؛ برای طبقه‌های هم‌عرض</label></fieldset>
 {!s.equalWidth?<p className="bins-note">عرض‌ها برابر نیستند؛ برای مقایسهٔ سهم‌ها، نمودار با ارتفاع چگالی رسم می‌شود. ارتفاعِ تعداد روی عرض‌های نابرابر، مساحت متناسب با سهم نمی‌سازد.</p>:<p className="small-note">عرض‌ها برابرند؛ ارتفاع تعداد، فراوانی را مقایسه می‌کند. در نمایش چگالی، مساحت هر میله سهم آن طبقه است. مساحت نمودار تعداد را درصد نخوان.</p>}
 <BinPlot summary={s} chart={chart} selected={state.selected} onSelect={index=>dispatch({type:'select',index})}/><p className="small-note">با انتخاب میله یا شمارهٔ طبقه، مشاهده‌های همان طبقه را ببین. طبقه‌های خالی یا بسیار باریک را از جدول انتخاب کن. برچسب‌های محور و ارتفاع کوتاه شده‌اند؛ مرزهای کامل در جدول آمده‌اند.</p>
 <div className="table-scroll bins-table"><table><caption>همهٔ طبقه‌ها، حتی طبقه‌های خالی؛ مخرج سهم‌ها {number(s.n)} مشاهده است</caption><thead><tr><th scope="col">طبقه</th><th scope="col">بازهٔ دقیق</th><th scope="col">عرض</th><th scope="col">تعداد</th><th scope="col">سهم</th><th scope="col">چگالی</th><th scope="col">مساحت چگالی</th><th scope="col">تعداد تجمعی</th></tr></thead><tbody>{s.bins.map((b,i)=><tr key={i} className={state.selected===i?'bins-selected':''}><th scope="row"><button className="text-button" aria-label={'انتخاب طبقهٔ '+number(i+1)} aria-pressed={state.selected===i} onClick={()=>dispatch({type:'select',index:state.selected===i?null:i})}>{number(i+1)}</button></th><td><bdi dir="ltr">{binInterval(b)}</bdi></td><td><bdi>{distributionValue(b.width)}</bdi></td><td>{number(b.count)}</td><td>{fmt(b.share*100)}٪</td><td>{binHeight(b.density)}</td><td>{fmt(b.share*100)}٪</td><td>{number(b.cumulative)}</td></tr>)}</tbody></table></div>
 {selected?<div className="bins-note" role="status"><h3>طبقهٔ {number(state.selected+1)}: <bdi dir="ltr">{binInterval(selected)}</bdi></h3><p>{selected.last?'این آخرین طبقه است؛ هر دو مرز شامل می‌شوند.':'مرز چپ شامل و مرز راست خارج است؛ عدد روی مرز راست به طبقهٔ بعدی می‌رود.'}</p><p>سهم = {number(selected.count)} ÷ {number(s.n)} = {fmt(selected.share*100)}٪. چگالی ≈ {binHeight(selected.density)}؛ عرض × چگالی = سهم. واحد چگالی، معکوسِ واحد محور افقی است.</p>{selected.count?<ul className="bins-members">{selected.members.map(m=><li key={m.index}>مشاهدهٔ {number(m.index+1)}: <bdi>{distributionValue(m.value)}</bdi></li>)}</ul>:<p>هیچ مشاهده‌ای در این بازه نیست؛ تعداد، سهم و چگالی صفرند.</p>}<p className="small-note">شماره‌ها از ترتیب اصلی داده‌اند؛ هیچ مشاهده‌ای حذف، جابه‌جا یا دوبار شمرده نشده است.</p></div>:null}
 <div className="bins-area"><strong>سهم همهٔ طبقه‌ها: ۱۰۰٪</strong><p>در نمایش چگالی، مجموع مساحت‌ها به‌طور نظری ۱ است؛ ارتفاع‌ها لزوماً جمعشان ۱ نیست و می‌توانند از ۱ بزرگ‌تر باشند. جدول سهم و مساحت را به درصد نمایش می‌دهد؛ ارتفاع، درصد نیست.</p></div>
 </section>;
}
export function BinWorkspace({state,dispatch,navigate,onDownload}){
 const a=analyzeBins(state),p=binPresets[state.preset];
 return <section id="lab-panel" role="tabpanel" aria-labelledby="tab-bins"><div className="dist-intro"><h2>ارتفاع را ببین؛ مساحت را بخوان.</h2><p>برای متغیر کمی، بازه‌ها را تغییر بده و ببین همان داده‌ها چگونه ظاهر دیگری پیدا می‌کنند. عرض‌های متفاوت را با چگالی مقایسه کن.</p></div><div className="bins-layout"><aside className="dist-card bins-editor"><h3>داده‌ها و مرزها</h3><label htmlFor="bins-preset">مثال ساختگی<select id="bins-preset" value={state.preset} onChange={e=>dispatch({type:'preset',id:e.target.value})}>{Object.entries(binPresets).map(([id,p])=><option key={id} value={id}>{p.label}</option>)}</select></label><p><strong>در نمونهٔ اولیه:</strong> {p.explanation}</p><label htmlFor="bins-data">مقدارهای اصلی<textarea id="bins-data" dir="ltr" rows="4" maxLength="10000" value={state.xtext} aria-invalid={Boolean(a.data.error)} onChange={e=>dispatch({type:'data',field:'xtext',value:e.target.value})}/></label>{a.data.error?<p className="error-message">داده: {a.data.error}</p>:null}<label htmlFor="bins-edges">مرزها؛ از کوچک به بزرگ<textarea id="bins-edges" dir="ltr" rows="3" maxLength="10000" value={state.etext} aria-invalid={Boolean(a.edges.error||(!a.data.error&&!a.summary))} onChange={e=>dispatch({type:'data',field:'etext',value:e.target.value})}/></label>{a.edges.error?<p className="error-message">مرز: {a.edges.error}</p>:null}<p className="small-note">۱ تا ۲۰۰ مقدار و ۳ تا ۱۳ مرز (۲ تا ۱۲ طبقه)، بین منفی و مثبت یک میلیارد. رقم فارسی و نمایش علمی پذیرفته می‌شود. ورودی خالی، گمشده یا نامعتبر، صفر فرض نمی‌شود.</p><div className="bins-edge-actions"><button className="button secondary compact" onClick={()=>dispatch({type:'edges',alternative:false})}>مرزهای اولیهٔ مثال</button><button className="button secondary compact" onClick={()=>dispatch({type:'edges',alternative:true})}>مرزهای جایگزین؛ داده حفظ می‌شود</button></div><p className="small-note">این دو دکمه فقط مرزهای نمونه را می‌گذارند؛ فهرست فعلی داده‌ها حفظ می‌شود. اگر پوشش کافی نباشد، خطا نمایش می‌دهیم. تغییر مرزها میانگین و میانهٔ داده‌های اصلی را عوض نمی‌کند.</p><button className="text-button" onClick={()=>dispatch({type:'reset'})}>بازنشانی کامل همین مثال</button><p className="small-note">این بخش فقط تا هنگام بازبودن آن حفظ می‌شود و جزو پیشرفت دوره یا پشتیبان نیست. تغییر ورودی انتخاب طبقه را پاک می‌کند؛ انتخاب یا بازنشانی مثال، خودسنجی را هم از ابتدا شروع می‌کند.</p></aside>{a.summary?<BinResults state={state} summary={a.summary} dispatch={dispatch}/>:<section className="dist-card empty-state" role="alert"><h3>طبقه‌بندی معتبر لازم است</h3><p>{a.error}</p><p>تا اصلاح ورودی، جدول و نمودار قبلی نمایش داده نمی‌شوند.</p></section>}</div>
 <section className="dist-card bins-contract"><h2>هر مشاهده، دقیقاً یک طبقه</h2><p>قرارداد این ابزار <bdi dir="ltr">[a,b)</bdi> است: مرز چپ داخل و مرز راست خارج. فقط آخرین طبقه <bdi dir="ltr">[a,b]</bdi> است تا بزرگ‌ترین مرز هم شمارش شود. مرزها باید همهٔ داده‌ها را بپوشانند.</p><div className="formula" dir="ltr">density = (count / n) / width<br/>area = density × width = count / n</div><p>مثلاً عرض ۴ و چگالی ۰٫۱، مساحت ۰٫۴ یا سهم ۴۰٪ می‌سازد. ارتفاع ۰٫۱ به‌تنهایی سهم ۱۰٪ نیست. هیستوگرام بازه‌های یک متغیر کمی را نشان می‌دهد؛ برای نام گروه‌ها یا طبقه‌های ترتیبی، نمودار میله‌ای فراوانی مناسب است.</p><p className="small-note">عددها با دقت Number مرورگر پذیرفته می‌شوند؛ مرزها قبل از شمارش گرد نمی‌شوند و تلورانس مرزی اضافه نمی‌کنیم. اگر عددی نزدیک مرز است، مقدار پذیرفته‌شدهٔ آن را بررسی کن. قرارداد نرم‌افزارها و تلورانس آن‌ها ممکن است متفاوت باشد. مساحت محاسبه‌شده می‌تواند به‌علت ممیز شناور اختلاف بسیار کوچکی با ۱ داشته باشد.</p></section>
 <section className="dist-card dist-checks"><h2>خودت را بسنج</h2><p>این سه سؤال دربارهٔ مثال‌های ثابت‌اند؛ تغییر داده‌ها پاسخ آن‌ها را تغییر نمی‌دهد و نتیجه مستقل از پیشرفت دوره است.</p>{binChecks.map(q=><form key={q.id} onSubmit={e=>{e.preventDefault();dispatch({type:'check',id:q.id});}}><fieldset><legend>{q.question}</legend>{q.options.map((text,value)=><label key={value}><input type="radio" name={'bins-check-'+q.id} checked={state.answers[q.id]===value} onChange={()=>dispatch({type:'answer',id:q.id,value})}/><span>{text}</span></label>)}</fieldset><button className="button secondary compact" type="submit" disabled={!Number.isInteger(state.answers[q.id])||state.checked[q.id]}>بررسی پاسخ</button>{state.checked[q.id]?<p role="status" className={'dist-check-feedback '+(state.answers[q.id]===q.correct?'correct':'retry')}>{q.feedback[state.answers[q.id]]}</p>:null}</form>)}</section>
 <section className="dist-card"><h2>شکل نمودار، به انتخاب مرزها هم وابسته است</h2><p>مرزهای جایگزین را امتحان کن. داده‌های خام، تعداد کل، میانگین و میانه ثابت می‌مانند؛ تعداد هر طبقه و ظاهر نمودار ممکن است عوض شوند. میانگین این صفحه از داده‌های اصلی به دست می‌آید؛ از مرکز طبقه‌ها برآورد نمی‌شود. یک ظاهر زنگوله‌ای به‌تنهایی نرمال‌بودن داده یا جامعه را اثبات نمی‌کند.</p><div className="dist-actions"><button className="button secondary" disabled={!a.summary} onClick={onDownload}>دریافت گزارش طبقه‌بندی</button><button className="text-button" onClick={()=>navigate('lesson',3,{section:'guide-idea'})}>مرور نمودارها در درس سوم</button><button className="text-button" onClick={()=>navigate('lab',0,{mode:'hist'})}>هیستوگرام مقدماتی با تعداد طبقه‌ها</button><button className="text-button" onClick={()=>navigate('lab',0,{mode:'ordinal'})}>فراوانی طبقه‌های ترتیبی</button></div><div className="bins-sources"><a href="https://www.itl.nist.gov/div898/handbook/eda/section3/eda33e.htm" target="_blank" rel="noreferrer">چگالی و مساحت هیستوگرام · NIST</a><a href="https://stat.ethz.ch/R-manual/R-devel/library/graphics/html/hist.html" target="_blank" rel="noreferrer">قرارداد مرزها و طبقه‌های نابرابر · R</a></div></section>
 </section>;
}
export default function HistogramBins({navigate=()=>{}}){const [state,dispatch]=useReducer(binReducer,undefined,initialBinState);function download(){const url=URL.createObjectURL(new Blob(['\uFEFF'+buildBinReport(state)],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='amar-histogram-bins.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}return <BinWorkspace state={state} dispatch={dispatch} navigate={navigate} onDownload={download}/>;}
