import React from 'react';
import {ChartColumn,ClipboardList,Check,Table2,ChartLine,ChartPie,ChartScatter,Equal,Target,Presentation} from 'lucide-react';
import {number,fmt} from './format.js';
import {BASE_X,describe,histogram} from './stats.js';
const sample=[4,...[1,2,4,6,9,12,10,7,4,2,1].flatMap((count,i)=>Array(count).fill(4+(i+.5)*8/11)),12];
const bins=histogram(sample,11),stats=describe(sample);
const lessonIcons=[ChartColumn,Table2,ChartLine,ChartPie,ChartColumn,Equal,ChartLine,Target,ChartScatter,Presentation];
export default function Home({course,progress,navigate}){
 const next=course.lessons.find(l=>!progress.lessons.includes(l.id))||course.lessons[0];
 return <><div className="page-heading"><h1>آمار را با تجربه یاد بگیر</h1><p>از داده‌های خام تا تحلیل و گزارش، قدم‌به‌قدم.</p></div>
 <div className="welcome-grid"><section className="journey-panel"><h2>مسیر یادگیری شما</h2><h3>جلسهٔ {number(next.id)} · {next.title}</h3><p>{next.description}. با مثال‌های روان‌شناختی پیش برو و آموخته‌هایت را در تمرین‌ها به کار بگیر.</p><button className="button amber" onClick={()=>navigate('lesson',next.id)}>{progress.lessons.length?'ادامهٔ یادگیری':'شروع یادگیری'}</button></section>
 <button className="chart-preview" onClick={()=>navigate('lab')} aria-label="باز کردن آزمایشگاه تعاملی آمار"><div className="chart-preview-heading"><h2>داده‌ها را لمس کن</h2><p>آزمایشگاه تعاملی آمار</p></div><svg viewBox="0 0 600 230" role="img" aria-label="هیستوگرام نمونهٔ آموزشی ساعات خواب"><line x1="44" y1="184" x2="580" y2="184" stroke="#86919e"/><line x1="44" y1="20" x2="44" y2="184" stroke="#86919e"/>{[0,4,8,12].map(n=><g key={n}><text x="28" y={184-n*12+5} textAnchor="middle">{number(n)}</text></g>)}{bins.map((b,i)=><rect key={i} x={46+i*48} y={184-b.count*12} width="47" height={b.count*12} fill="#28726a"/>)}<line x1={44+(stats.mean-4)/8*528} x2={44+(stats.mean-4)/8*528} y1="18" y2="184" stroke="#e9a83b" strokeWidth="3" strokeDasharray="6 5"/><text x="308" y="16" textAnchor="middle" fill="#bd7c0b">میانگین = {fmt(stats.mean)}</text>{[4,6,8,10,12].map((n,i)=><text key={n} x={46+i*132} y="208" textAnchor="middle">{number(n)}</text>)}<text x="305" y="230" textAnchor="middle">ساعت خواب · دادهٔ ساختگی آموزشی</text></svg></button></div>
 <section className="lesson-list-section"><div className="section-heading"><h2>ده قدم تا تحلیل داده</h2><span>{number(progress.lessons.length)} از ۱۰ جلسه خوانده شده</span></div><div className="lesson-list">{course.lessons.map(l=>{const Icon=lessonIcons[l.id-1];return <article className="lesson-row" key={l.id}><span className={'lesson-number '+(progress.lessons.includes(l.id)?'complete':'')}>{progress.lessons.includes(l.id)?<Check size={20}/>:number(l.id)}</span><h3><Icon size={22}/>{l.title}</h3><p>{l.description}</p><span className="exercise-count"><ClipboardList size={19}/>{number(l.exercises.length)} تمرین</span><button className="button compact" onClick={()=>navigate('lesson',l.id)}>مطالعه</button></article>;})}</div></section></>;
}
