import React,{useMemo,useState} from 'react';
import {Download,BookOpen,Search} from 'lucide-react';
import {Blocks} from './Content.jsx';
import {download,number} from './format.js';
function textOf(block){return block.text||block.rows.flat().join(' ');}
export default function Library({course,navigate}){
 const [selected,setSelected]=useState(null),[query,setQuery]=useState(''),[kind,setKind]=useState('all');
 const documents=useMemo(()=>[...course.lessons.map(l=>({id:'lesson-'+l.id,title:'جزوهٔ جلسه · '+l.title,kind:'lesson',file:l.files[0],blocks:l.blocks,lessonId:l.id})),...course.library.map(l=>({...l,kind:l.kind||'support'}))],[course]);
 const docs=documents.filter(d=>(kind==='all'||d.kind===kind)&&(!query||[d.title,...d.blocks.map(textOf)].join(' ').includes(query)));
 const active=documents.find(d=>d.id===selected);
 if(active)return <><button className="text-button" onClick={()=>setSelected(null)}>بازگشت به کتابخانه</button><div className="page-heading"><h1>{active.title}</h1></div><div className="reader-actions"><a className="button" href={download(active.file)} download><Download size={18}/>دریافت فایل Word</a>{active.kind==='lesson'?<button className="button secondary" onClick={()=>navigate('lesson',active.lessonId)}>نمای مطالعهٔ جلسه</button>:null}</div><Blocks blocks={active.blocks}/></>;
 return <><div className="page-heading"><h1>کتابخانهٔ دوره</h1><p>متن کامل ۳۲ سند آموزشی، جدول‌ها، کاربرگ‌ها و راهنمای مدرس.</p></div><div className="library-download"><div><h2>بستهٔ کامل دوره</h2><p>فایل‌های Word، پیوست، مثال SPSS و گزارش تأیید Excel در نسخهٔ ۱۳.</p></div><a className="button" href={download('course-v13.zip')} download><Download size={18}/>دریافت همهٔ فایل‌ها</a></div><div className="software-resources"><a href={download('مثال_پیوست_SPSS.sps')} download>فایل فرمان SPSS</a><a href={download('گزارش_اجرای_Excel_نسخه_13.md')} download>گزارش اجرای Excel</a><span>۱۱ فرمول در Excel تأیید شده‌اند؛ اجرای SPSS تأیید نشده است.</span></div><div className="filter-bar library-filter"><label>نوع سند<select value={kind} onChange={e=>setKind(e.target.value)}><option value="all">همهٔ سندها</option><option value="lesson">جزوهٔ دانشجو</option><option value="worksheet">کاربرگ تمرین</option><option value="teacher">راهنمای مدرس و پاسخ‌نامه</option><option value="support">نقشهٔ راه و پیوست</option></select></label><label className="search-label">جست‌وجو در متن کامل<div className="search-field"><Search size={18}/><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="مثلاً چارک، نماد یا Excel"/></div></label></div><div className="results-label" aria-live="polite">{number(docs.length)} سند</div><div className="document-list">{docs.map(d=><article key={d.id}><BookOpen size={22}/><div><h2>{d.title}</h2><p>{d.kind==='teacher'?'پاسخ‌های معیار، نکات تصحیح و راهنمای تدریس':d.kind==='worksheet'?'صورت سؤال‌ها برای حل مستقل':d.kind==='lesson'?'آموزش، مثال‌ها و جدول‌های جلسه':'راهنمای مکمل دوره'}</p></div><button className="button compact secondary" onClick={()=>{setSelected(d.id);window.scrollTo({top:0,behavior:'instant'});}}>خواندن</button><a className="icon-button" href={download(d.file)} download aria-label={'دریافت '+d.title}><Download size={18}/></a></article>)}</div>{!docs.length?<div className="empty-state"><h2>سندی پیدا نشد</h2><p>نوع سند یا عبارت جست‌وجو را تغییر دهید.</p></div>:null}</>;
}
