import React from 'react';
import {createRoot} from 'react-dom/client';
import App from './App.jsx';
import './styles.css';
import './editorial.css';
import './groupComparison.css';
import './weightedMean.css';
import './coachedPractice.css';
import './project.css';
import './distributionComparison.css';
import './robustness.css';
import './ordinal.css';
createRoot(document.getElementById('root')).render(<App/>);
