import React,{useMemo,useState} from 'react';
import {Search,Check,RotateCcw,Eye,EyeOff} from 'lucide-react';
import {Blocks} from './Content.jsx';
import {number} from './format.js';
function normalize(text){return text.replace(/ي/g,'ی').replace(/ك/g,'ک').replace(/[\u200c\u200e\u200f]/g,' ').trim().toLowerCase();}
function Question({question,progress,setProgress}){
 const [revealed,setRevealed]=useState(false);
 const solved=progress.solved.includes(question.id),review=progress.review.includes(question.id);
 const draft=progress.drafts[question.id]||'';
 function assess(status){setProgress(p=>({...p,solved:status==='solved'?[...p.solved.filter(id=>id!==question.id),question.id]:p.solved.filter(id=>id!==question.id),review:status==='review'?[...p.review.filter(id=>id!==question.id),question.id]:p.review.filter(id=>id!==question.id)}));}
 return <article className={'question '+(solved?'solved':'')}><div className="question-top"><span>جلسهٔ {number(question.lessonId)} · تمرین {number(question.number)}</span><span className="question-type">{question.main?'اصلی':'تکمیلی'}{solved?' · حل شد':review?' · نیاز به مرور':''}</span></div><h2>{question.text}</h2><details className="draft-section"><summary>پاسخ خودم را می‌نویسم{draft?' · یادداشت ذخیره‌شده':''}</summary><label htmlFor={'draft-'+question.id}>پاسخ شما</label><textarea id={'draft-'+question.id} value={draft} rows="4" onChange={e=>{const value=e.target.value;setProgress(p=>({...p,drafts:{...p.drafts,[question.id]:value}}));}} placeholder="استدلال یا محاسبه‌ات را اینجا بنویس…" maxLength="8000"/><p className="small-note">پاسخ روی همین مرورگر ذخیره می‌شود. ارزیابی این تمرین با مقایسهٔ خودتان انجام می‌شود.</p></details><button className="text-button answer-toggle" onClick={()=>setRevealed(v=>!v)} aria-expanded={revealed} aria-controls={'answer-'+question.id}>{revealed?<EyeOff size={18}/>:<Eye size={18}/>} {revealed?'پنهان‌کردن پاسخ':'نمایش پاسخ تشریحی'}</button>{revealed?<div id={'answer-'+question.id} className="answer-panel"><Blocks blocks={question.answer}/><div className="assessment"><span>پس از مقایسهٔ پاسخ:</span><button className={'button compact '+(solved?'':'secondary')} aria-pressed={solved} onClick={()=>assess(solved?'clear':'solved')}><Check size={17}/>درست حل کردم</button><button className={'button compact '+(review?'':'secondary')} aria-pressed={review} onClick={()=>assess(review?'clear':'review')}><RotateCcw size={17}/>نیاز به مرور دارم</button></div></div>:null}</article>;
}
export default function Practice({course,initialLesson=0,progress,setProgress}){
 const [lesson,setLesson]=useState(String(initialLesson||0)),[type,setType]=useState('all'),[status,setStatus]=useState('all'),[query,setQuery]=useState(''),[page,setPage]=useState(1);
 const all=useMemo(()=>course.lessons.flatMap(l=>l.exercises.map(q=>({...q,lessonId:l.id}))),[course]);
 const found=useMemo(()=>all.filter(q=>(lesson==='0'||q.lessonId===Number(lesson))&&(type==='all'||(type==='main'?q.main:!q.main))&&(status==='all'||(status==='solved'?progress.solved.includes(q.id):status==='review'?progress.review.includes(q.id):!progress.solved.includes(q.id)))&&normalize(q.text).includes(normalize(query))),[all,lesson,type,status,query,progress.solved,progress.review]);
 const pages=Math.max(1,Math.ceil(found.length/12)),safePage=Math.min(page,pages),slice=found.slice((safePage-1)*12,safePage*12);
 function filter(setter,value){setter(value);setPage(1);}
 return <><div className="page-heading"><h1>بانک تمرین</h1><p>۴۸۰ فرصت برای تمرین؛ ۳۰۰ تمرین اصلی و ۱۸۰ تمرین تکمیلی.</p></div><div className="practice-summary"><span><strong>{number(progress.solved.length)}</strong> تمرین حل‌شده</span><span><strong>{number(progress.review.length)}</strong> برای مرور دوباره</span><span>خودارزیابی پس از دیدن پاسخ معیار</span></div><div className="filter-bar"><label>جلسه<select value={lesson} onChange={e=>filter(setLesson,e.target.value)}><option value="0">همهٔ جلسه‌ها</option>{course.lessons.map(l=><option key={l.id} value={l.id}>{number(l.id)} · {l.title}</option>)}</select></label><label>مسیر تمرین<select value={type} onChange={e=>filter(setType,e.target.value)}><option value="all">همهٔ تمرین‌ها</option><option value="main">اصلی</option><option value="extra">تکمیلی</option></select></label><label>وضعیت<select value={status} onChange={e=>filter(setStatus,e.target.value)}><option value="all">همهٔ وضعیت‌ها</option><option value="unsolved">حل‌نشده</option><option value="solved">حل‌شده</option><option value="review">نیاز به مرور</option></select></label><label className="search-label">جست‌وجو در سؤال‌ها<div className="search-field"><Search size={18}/><input type="search" value={query} onChange={e=>filter(setQuery,e.target.value)} placeholder="مثلاً میانگین یا اضطراب"/></div></label></div><div className="results-label" aria-live="polite">{number(found.length)} تمرین · صفحهٔ {number(safePage)} از {number(pages)}</div><div className="questions">{slice.length?slice.map(q=><Question key={q.id} question={q} progress={progress} setProgress={setProgress}/>):<div className="empty-state"><h2>تمرینی با این انتخاب پیدا نشد</h2><p>عبارت جست‌وجو یا فیلترها را تغییر بده.</p><button className="button secondary" onClick={()=>{setLesson('0');setType('all');setStatus('all');setQuery('');setPage(1);}}>نمایش همهٔ تمرین‌ها</button></div>}</div><nav className="pagination" aria-label="صفحه‌های تمرین"><button className="button secondary" disabled={safePage===1} onClick={()=>{setPage(safePage-1);window.scrollTo({top:0,behavior:'instant'});}}>صفحهٔ قبل</button><span>{number(safePage)} / {number(pages)}</span><button className="button secondary" disabled={safePage===pages} onClick={()=>{setPage(safePage+1);window.scrollTo({top:0,behavior:'instant'});}}>صفحهٔ بعد</button></nav></>;
}
