import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {latin} from './stats.js';
import {PROJECT_KEY,projectCase,projectRows,reportFields,setupQuestions,initialProject,expectedDecision,assessProjectData,projectAnalysis,projectReportStatus,projectReducer,normalizeProject,loadProjectDraft,saveProjectDraft,buildProjectReport} from './project.js';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-12,`${a} != ${b}`);
const reduce=(state,type,extra={})=>projectReducer(state,{type,...extra});
function quality(){let state=initialProject();for(const row of projectRows)state=reduce(state,'decision',{id:row.id,value:expectedDecision(row)});return reduce(state,'checkData');}
function methods(){let state=quality();for(const q of setupQuestions)state=reduce(state,'setup',{id:q.id,value:q.correct});return reduce(state,'checkSetup');}
function interpreted(){return reduce(reduce(methods(),'interpretation',{value:'negative'}),'checkAnalysis');}
function reviewed(){let state=interpreted();for(const field of reportFields){state=reduce(state,'report',{id:field.id,value:'نوشتهٔ آزمایشیِ کاربر'});state=reduce(state,'review',{id:field.id,value:true});}return reduce(state,'stage',{value:3});}
function memory(){const values=new Map();return {values,getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value)};}

test('project raw rows exactly match lesson ten original table',()=>{const course=JSON.parse(readFileSync(new URL('../public/course.json',import.meta.url),'utf8'));const table=course.lessons[9].blocks.find(block=>block.type==='table');assert.deepEqual(projectRows,table.rows.slice(1).map(([id,group,sleep,stress])=>({id:Number(latin(id)),group,sleep:sleep==='مفقود'?null:Number(latin(sleep)),stress:Number(latin(stress))})));});
test('quality distinguishes missing, zero and invalid range, keeps all original pairs',()=>{const original=JSON.stringify(projectRows);assert.equal(projectAnalysis(initialProject()),null);const wrong=assessProjectData(initialProject().decisions);assert.deepEqual(wrong.issues.map(issue=>issue.id),[9,10]);assert.equal(expectedDecision({sleep:0,stress:0}),'include');assert.equal(expectedDecision({sleep:24,stress:2}),'include');assert.equal(expectedDecision({sleep:null,stress:0}),'missing');assert.equal(expectedDecision({sleep:25,stress:2}),'range');const state=quality();assert.equal(state.dataChecked,true);assert.deepEqual(projectAnalysis(state).rows.map(row=>row.id),[1,2,3,4,5,6,7,8]);assert.equal(JSON.stringify(projectRows),original);const invalid=reduce(state,'decision',{id:1,value:'missing'});assert.equal(projectAnalysis(invalid),null);assert.deepEqual(assessProjectData(invalid.decisions).issues.map(issue=>issue.id),[1]);});
test('confirmed analysis uses sample SD, type seven quartiles and paired correlation',()=>{const a=projectAnalysis(quality());assert.equal(a.pair.n,8);assert.equal(a.sleep.mean,7);assert.equal(a.sleep.median,7);near(a.sleep.variance,12/7);near(a.sleep.sd,Math.sqrt(12/7));assert.equal(a.sleep.q1,6);assert.equal(a.sleep.q3,8);assert.equal(a.sleep.iqr,2);assert.equal(a.stress.mean,6.5);near(a.stress.sd,Math.sqrt(6));near(a.pair.r,-22/Math.sqrt(504));assert.deepEqual(a.groups.map(group=>[group.group,group.n,group.sleep.mean,group.stress.mean]),[['الف',4,6,8.5],['ب',4,8,4.5]]);assert.deepEqual(a.y,[10,9,8,7,6,5,4,3]);});
test('navigation gates each stage, setup and interpretation provide specific feedback',()=>{let state=initialProject();for(const stage of [1,2,3,-1,1.5])assert.equal(reduce(state,'stage',{value:stage}),state);assert.equal(reduce(state,'checkSetup'),state);assert.equal(reduce(state,'checkAnalysis'),state);state=quality();assert.equal(reduce(state,'stage',{value:1}).stage,1);assert.equal(reduce(state,'stage',{value:2}),state);const wrong=reduce(reduce(state,'setup',{id:'goal',value:'cause'}),'checkSetup');assert.equal(wrong.setupChecked,false);assert.equal(wrong.feedback.messages.length,3);state=methods();assert.equal(reduce(state,'stage',{value:2}).stage,2);assert.equal(reduce(state,'stage',{value:3}),state);const percent=reduce(reduce(state,'interpretation',{value:'percent'}),'checkAnalysis');assert.equal(percent.analysisChecked,false);assert.match(percent.feedback.messages[0],/درصد افراد نیست/);const cause=reduce(reduce(state,'interpretation',{value:'cause'}),'checkAnalysis');assert.match(cause.feedback.messages[0],/علت/);assert.equal(reduce(interpreted(),'stage',{value:3}).stage,3);});
test('upstream edits preserve report but invalidate later checks and self review',()=>{const state=reviewed();assert.equal(projectReportStatus(state).ready,true);const data=reduce(state,'decision',{id:9,value:'include'});assert.equal(data.stage,0);assert.equal(data.dataChecked,false);assert.equal(data.setupChecked,false);assert.equal(data.analysisChecked,false);assert.ok(Object.values(data.review).every(value=>value===false));assert.deepEqual(data.report,state.report);const setup=reduce(state,'setup',{id:'chart',value:'hist'});assert.equal(setup.stage,1);assert.equal(setup.dataChecked,true);assert.equal(setup.setupChecked,false);assert.equal(setup.analysisChecked,false);assert.ok(Object.values(setup.review).every(value=>!value));const interpretation=reduce(state,'interpretation',{value:'cause'});assert.equal(interpretation.analysisChecked,false);assert.equal(interpretation.review.interpretation,false);assert.equal(interpretation.review.limits,false);const text=reduce(state,'report',{id:'summary',value:'متن جدید'});assert.equal(text.review.summary,false);assert.equal(text.review.question,true);assert.equal(projectReportStatus(text).ready,false);});
test('report completeness is manual self review, never semantic grading of free text',()=>{let state=interpreted();assert.equal(projectReportStatus(state).missing.length,5);for(const field of reportFields)state=reduce(state,'review',{id:field.id,value:true});assert.equal(projectReportStatus(state).ready,false);state=reduce(state,'report',{id:'question',value:'   '});assert.equal(projectReportStatus(state).missing.length,5);const complete=reviewed();assert.equal(projectReportStatus(complete).ready,true);assert.match(buildProjectReport(complete),/^آمارآموز — گزارش آموزشی با خودبازبینی کاربر/);assert.match(buildProjectReport(complete),/تأیید علمی خودکار متن کاربر نیست/);});
test('draft export suppresses unchecked numerical output, final export retains original precision and pair order',()=>{assert.match(buildProjectReport(initialProject()),/پیش‌نویس گزارش/);assert.doesNotMatch(buildProjectReport(initialProject()),/پیرسون:/);assert.doesNotMatch(buildProjectReport(quality()),/پیرسون:/);const text=buildProjectReport(methods());assert.match(text,/پیش‌نویس گزارش/);assert.match(text,/پیرسون:/);assert.match(text,/n−1/);assert.ok(text.includes(projectRows.slice(0,8).map(row=>`${row.id},${row.group},${row.sleep},${row.stress}`).join('\n')));assert.ok(!text.includes('10,ب,25,2'));assert.match(text,/شناسهٔ ۱۰: کنارگذاشتن مقدار نامعتبر/);});
test('draft storage round trip is separate from learning state and revalidates flags',()=>{const store=memory();store.setItem('amar-academy:learning:v2','untouched');assert.equal(loadProjectDraft(store).blocked,false);const state=reviewed();assert.equal(saveProjectDraft(state,store),true);assert.equal(store.getItem('amar-academy:learning:v2'),'untouched');const loaded=loadProjectDraft(store);assert.equal(loaded.blocked,false);assert.equal(loaded.state.stage,3);assert.deepEqual(loaded.state.report,state.report);assert.equal(projectReportStatus(loaded.state).ready,true);const forged=normalizeProject({...initialProject(),stage:3,dataChecked:true,setupChecked:true,analysisChecked:true});assert.equal(forged.stage,0);assert.equal(forged.analysisChecked,false);assert.equal(projectAnalysis(forged),null);});
test('unreadable or future drafts and denied storage do not erase existing data',()=>{const store=memory();for(const raw of ['bad json',JSON.stringify({version:2,case:projectCase,state:reviewed()}),JSON.stringify({version:1,case:'unknown',state:reviewed()}),JSON.stringify({version:1,case:projectCase,state:[]}),JSON.stringify({version:1,case:projectCase,state:8})]){store.setItem(PROJECT_KEY,raw);const loaded=loadProjectDraft(store);assert.equal(loaded.blocked,true);assert.equal(store.getItem(PROJECT_KEY),raw);}const previous=JSON.stringify(reviewed());const denied={getItem:()=>{throw Error('denied');},setItem:()=>{throw Error('quota');}};assert.equal(loadProjectDraft(denied).blocked,true);assert.equal(saveProjectDraft(reviewed(),denied),false);assert.equal(JSON.stringify(reviewed()),previous);});
test('bounded draft normalization ignores unknown fields and invalid actions',()=>{const raw={...reviewed(),extra:'ignore',report:{...reviewed().report,question:'x'.repeat(4001)},review:{...reviewed().review,limits:'yes'},stage:99};const normalized=normalizeProject(raw);assert.equal(normalized.stage,3);assert.equal(normalized.report.question,'');assert.equal(normalized.review.limits,false);assert.ok(!Object.hasOwn(normalized,'extra'));const state=reviewed();for(const action of [{type:'decision',id:99,value:'include'},{type:'decision',id:1,value:'__proto__'},{type:'setup',id:'goal',value:'unknown'},{type:'interpretation',value:'unknown'},{type:'chart',value:'pie'},{type:'report',id:'summary',value:'a'.repeat(4001)},{type:'review',id:'limits',value:1}])assert.equal(projectReducer(state,action),state);assert.equal(reduce(state,'report',{id:'question',value:'x'.repeat(4000)}).report.question.length,4000);});
