import React,{useReducer} from 'react';
import {rankPresets,rankChecks,initialRankState,rankReducer,analyzeRanks,coefficientText,buildRankReport} from './rankCorrelation.js';
import {number} from './format.js';
import {distributionValue,distributionAxisLabels} from './distributionComparison.js';

function plotDomain(values,ranked,n){if(ranked)return {min:.5,max:n+.5};const min=Math.min(...values),max=Math.max(...values),pad=max>min?(max-min)*.07:1;return {min:min-pad,max:max+pad};}
export function RankScatter({x,y,ranked=false,selected,onSelect}){
 const xd=plotDomain(x,ranked,x.length),yd=plotDomain(y,ranked,y.length),sx=v=>112+(v-xd.min)/(xd.max-xd.min)*582,sy=v=>262-(v-yd.min)/(yd.max-yd.min)*238;
 return <svg className="rank-scatter" viewBox="0 0 720 330" role="group" aria-label={ranked?'نمودار رتبه‌های X و Y؛ هر نقطه یک جفت':'نمودار مقدارهای X و Y؛ هر نقطه یک جفت'}>{distributionAxisLabels(yd).map((tick,i)=><g key={i}><line x1="112" x2="694" y1={sy(tick.value)} y2={sy(tick.value)} stroke="#e2e6e5"/><text x="102" y={sy(tick.value)+4} textAnchor="end" direction="ltr">{tick.label}</text></g>)}<line x1="112" x2="694" y1="262" y2="262" stroke="#687783"/>{distributionAxisLabels(xd).map((tick,i)=><text key={i} x={sx(tick.value)} y="286" textAnchor={i===0?'start':i===4?'end':'middle'} direction="ltr">{tick.label}</text>)}<text x="400" y="318" textAnchor="middle">{ranked?'رتبهٔ X':'X'}</text><text transform="translate(20 150) rotate(-90)" textAnchor="middle">{ranked?'رتبهٔ Y':'Y'}</text>{x.map((value,i)=><circle key={i} cx={sx(value)} cy={sy(y[i])} r={selected===i?9:6} fill={selected===i?'#c58b36':'#28726a'} stroke="white" strokeWidth="2" role="button" tabIndex="0" aria-pressed={selected===i} aria-label={`جفت ${number(i+1)}؛ ${ranked?'رتبهٔ ':''}X ${distributionValue(value)}؛ ${ranked?'رتبهٔ ':''}Y ${distributionValue(y[i])}`} onClick={()=>onSelect(selected===i?null:i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(selected===i?null:i);}}}><title>{`جفت ${number(i+1)}؛ X=${distributionValue(value)}؛ Y=${distributionValue(y[i])}`}</title></circle>)}</svg>;
}
export function RankResults({state,analysis,dispatch}){
 const s=analysis.summary,quantitative=state.scale==='quantitative',index=state.selected,gx=Number.isInteger(index)?s.rx.groups[s.rx.byIndex[index]]:null,gy=Number.isInteger(index)?s.ry.groups[s.ry.byIndex[index]]:null;
 const select=index=>dispatch({type:'select',index});
 return <section className="dist-card rank-results"><h2>از مقدار هر جفت تا رابطهٔ رتبه‌ها</h2><div className="metric-strip"><div><span>جفت مشاهده</span><strong>{number(s.n)}</strong></div><div><span>اسپیرمن · رابطهٔ رتبه‌ها</span><strong>{coefficientText(s.spearman)}</strong></div>{quantitative?<div><span>پیرسون · رابطهٔ خطی مقدارها</span><strong>{coefficientText(s.pearson)}</strong></div>:null}</div><p>{quantitative?'پیرسون فاصله‌های مقدارهای کمی را به کار می‌گیرد؛ اسپیرمن پیرسونِ رتبه‌هاست و روند افزایشی یا کاهشی ترتیب را خلاصه می‌کند.':'در حالت ترتیبی فقط رابطهٔ رتبه‌ها را محاسبه می‌کنیم؛ میانگین کدها یا پیرسونِ کدهای طبقه‌ها در نتیجه نمایش داده نمی‌شود.'}</p>{s.spearman===null?<p className="rank-note" role="status">حداقل یکی از متغیرها ثابت است؛ رتبه‌های آن نیز ثابت‌اند و همبستگی تعریف نمی‌شود. این وضعیت، ضریب صفر نیست.</p>:null}
  <div className={'rank-plots '+(quantitative?'paired':'')}>{quantitative?<div><h3>مقدارهای اصلی</h3><RankScatter x={s.x} y={s.y} selected={index} onSelect={select}/></div>:null}<div><h3>همان جفت‌ها با رتبه‌های متوسط</h3><RankScatter x={s.rx.ranks} y={s.ry.ranks} ranked selected={index} onSelect={select}/></div></div><p className="small-note">هر نقطه یک جفت است. نقطه‌های هم‌مکان روی هم می‌افتند؛ در جدول هر جفت ردیف مستقل دارد. روی نقطه یا شمارهٔ ردیف بزن تا همان مشاهده در هر دو نمایش انتخاب شود. محورهای دو نمودار واحدهای متفاوت دارند؛ شیب یا فاصلهٔ ظاهری آن‌ها را مستقیم مقایسه نکن.</p>
  <div className="table-scroll rank-table"><table><caption>ردیف‌ها در ترتیب اصلی؛ X و Y هر مشاهده با هم حفظ شده‌اند</caption><thead><tr><th scope="col">جفت</th><th scope="col">{quantitative?'مقدار':'کد ترتیبی'} X</th><th scope="col">{quantitative?'مقدار':'کد ترتیبی'} Y</th><th scope="col">رتبهٔ X</th><th scope="col">رتبهٔ Y</th></tr></thead><tbody>{s.x.map((value,i)=><tr key={i} className={index===i?'rank-row-selected':''}><th scope="row"><button className="text-button" aria-label={'انتخاب جفت '+number(i+1)} aria-pressed={index===i} onClick={()=>select(index===i?null:i)}>{number(i+1)}</button></th><td>{distributionValue(value)}</td><td>{distributionValue(s.y[i])}</td><td>{distributionValue(s.rx.ranks[i])}</td><td>{distributionValue(s.ry.ranks[i])}</td></tr>)}</tbody></table></div>
  {gx&&gy?<div className="rank-note" role="status"><h3>جفت {number(index+1)} را از نزدیک ببین</h3><p>X={distributionValue(s.x[index])}: جایگاه {number(gx.start)}{gx.end!==gx.start?' تا '+number(gx.end):''} در ترتیب X؛ رتبهٔ متوسط {distributionValue(gx.rank)}.</p><p>Y={distributionValue(s.y[index])}: جایگاه {number(gy.start)}{gy.end!==gy.start?' تا '+number(gy.end):''} در ترتیب Y؛ رتبهٔ متوسط {distributionValue(gy.rank)}.</p><p>برای پیدا کردن رتبه، هر ستون جدا بررسی می‌شود؛ سپس رتبه‌ها به همین جفت اصلی برمی‌گردند. دو ستون مرتب‌شده را دوباره با هم جفت نمی‌کنیم.</p><button className="button secondary compact" onClick={()=>dispatch({type:'omit',index})}>مقایسهٔ آزمایشی بدون جفت {number(index+1)}</button></div>:null}
  {state.omitted!==null?<section className="rank-scenario"><h3>سناریوی بدون جفت {number(state.omitted+1)}</h3><p>نتیجهٔ کامل، نمودارها و جدول بالا حفظ شده‌اند. فقط برای مقایسه، این جفت از سناریو کنار گذاشته و رتبه‌های باقی‌مانده از نو ساخته می‌شوند.</p>{analysis.scenario?<div className="metric-strip"><div><span>جفت‌های سناریو</span><strong>{number(analysis.scenario.n)}</strong></div><div><span>اسپیرمن سناریو</span><strong>{coefficientText(analysis.scenario.spearman)}</strong></div>{quantitative?<div><span>پیرسون سناریو</span><strong>{coefficientText(analysis.scenario.pearson)}</strong></div>:null}</div>:<p role="status">کمتر از دو جفت باقی می‌ماند؛ همبستگی سناریو تعریف نمی‌شود.</p>}<p className="small-note">تغییر ضریب به‌تنهایی خطا بودن یک مشاهده یا مجوز حذف آن نیست. ثبت، زمینه و دلیل هر تصمیم باید جدا بررسی شوند.</p><button className="text-button" onClick={()=>dispatch({type:'omit',index:null})}>بستن سناریو و بازگشت به همهٔ جفت‌ها</button></section>:null}
  <details className="rank-calculation"><summary>اسپیرمن دقیقاً چگونه محاسبه شد؟</summary><ol><li>در هر ستون، کوچک‌ترین مقدار رتبهٔ ۱ می‌گیرد؛ برای تساوی‌ها، میانگین جایگاه‌ها را می‌گیریم.</li><li>رتبه‌ها را به ردیف‌های اصلی برمی‌گردانیم؛ میانگین رتبه‌های هر ستون {distributionValue(s.mean)} است.</li><li>پیرسون را روی همین دو ستون رتبه حساب می‌کنیم.</li></ol><p>مجموع مربع انحراف رتبه‌های X: {distributionValue(s.ssX)}؛ برای Y: {distributionValue(s.ssY)}؛ مجموع حاصل‌ضرب انحراف رتبه‌های هر جفت: {distributionValue(s.cross)}.</p><div className="formula" dir="ltr">rₛ = Σ[(Rₓ − R̄ₓ)(Rᵧ − R̄ᵧ)] / √(Σ(Rₓ − R̄ₓ)² × Σ(Rᵧ − R̄ᵧ)²)</div><p className="small-note">اگر یکی از مجموع مربع‌ها صفر باشد، ضریب تعریف نمی‌شود. فرمول کوتاهِ ۱−۶Σd²/[n(n²−۱)] برای حالت بدون رتبهٔ برابر است؛ این ابزار برای تساوی‌ها از پیرسونِ رتبه‌های متوسط استفاده می‌کند.</p></details>
 </section>;
}
export function RankWorkspace({state,dispatch,navigate,onDownload}){
 const analysis=analyzeRanks(state);
 return <section id="lab-panel" role="tabpanel" aria-labelledby="tab-ranks"><div className="dist-intro"><h2>رابطهٔ مقدارها یا رابطهٔ ترتیب‌ها؟</h2><p>جفت‌ها را حفظ کن، رتبه‌های برابر را ببین و اسپیرمن را از روی رتبه‌ها بساز. برای دادهٔ کمی، آن را با پیرسون و شکل نمودار مقایسه کن.</p></div><div className="rank-layout"><aside className="dist-card rank-editor"><h3>داده‌های جفت‌شده</h3><label htmlFor="rank-preset">مثال ساختگی<select id="rank-preset" value={state.preset} onChange={e=>dispatch({type:'preset',id:e.target.value})}>{Object.entries(rankPresets).map(([id,p])=><option key={id} value={id}>{p.label}</option>)}</select></label><p><strong>در نمونهٔ اولیه:</strong> {rankPresets[state.preset].explanation}</p><label htmlFor="rank-scale">معنای عددها<select id="rank-scale" value={state.scale} onChange={e=>dispatch({type:'scale',value:e.target.value})}><option value="quantitative">هر دو کمی؛ فاصله‌های عددی معنادار</option><option value="ordinal">حداقل یکی ترتیبی؛ فقط ترتیب را به کار ببر</option></select></label><p className="small-note">در حالت ترتیبی، کد بزرگ‌تر باید نشان‌دهندهٔ طبقهٔ بالاتر باشد و کدهای برابر همان طبقه باشند. کد دلخواه اسمی، مثل شهر یا گروه بدون ترتیب، برای این ابزار مناسب نیست.</p><label htmlFor="rank-x">X؛ یک مقدار برای هر مشاهده<textarea id="rank-x" dir="ltr" rows="5" value={state.xtext} maxLength="10000" aria-invalid={Boolean(analysis.x.error)} onChange={e=>dispatch({type:'data',field:'xtext',value:e.target.value})}/></label>{analysis.x.error?<p className="error-message">X: {analysis.x.error}</p>:null}<label htmlFor="rank-y">Y؛ به همان ترتیب مشاهده‌های X<textarea id="rank-y" dir="ltr" rows="5" value={state.ytext} maxLength="10000" aria-invalid={Boolean(analysis.y.error)} onChange={e=>dispatch({type:'data',field:'ytext',value:e.target.value})}/></label>{analysis.y.error?<p className="error-message">Y: {analysis.y.error}</p>:null}<p className="small-note">هر دو فهرست باید کامل و هم‌اندازه باشند: ۲ تا ۲۰۰ جفت، عدد معتبر بین منفی و مثبت یک میلیارد. رقم فارسی هم پذیرفته می‌شود. خانهٔ خالی یا دادهٔ گمشده به صفر تبدیل نمی‌شود؛ جفت‌ها را بررسی کن.</p><button className="button secondary" onClick={()=>dispatch({type:'reset'})}>بازنشانی همین مثال</button><p className="small-note">ورودی‌ها، انتخاب جفت و خودسنجی فقط تا هنگام بازبودن این بخش حفظ می‌شوند؛ جزو پشتیبان یا پیشرفت دوره نیستند. انتخاب یا بازنشانی مثال، این بخش را از ابتدا شروع می‌کند. تغییر فهرست‌ها، انتخاب جفت و سناریوی قبلی را پاک می‌کند.</p></aside>{analysis.summary?<RankResults state={state} analysis={analysis} dispatch={dispatch}/>:<section className="dist-card empty-state" role="alert"><h3>جفت‌های معتبر لازم است</h3><p>{analysis.error}</p><p>تا اصلاح ورودی، نمودار و ضریب قبلی نمایش داده نمی‌شوند.</p></section>}</div>
 <section className="dist-card dist-checks"><h2>خودت را بسنج</h2><p>این سؤال‌ها دربارهٔ مثال‌های ثابت‌اند و با دادهٔ بالای صفحه تغییر نمی‌کنند. نتیجهٔ آن‌ها مستقل از پیشرفت دوره است.</p>{rankChecks.map(q=><form key={q.id} onSubmit={e=>{e.preventDefault();dispatch({type:'check',id:q.id});}}><fieldset><legend>{q.question}</legend>{q.options.map((text,value)=><label key={value}><input type="radio" name={'rank-check-'+q.id} checked={state.answers[q.id]===value} onChange={()=>dispatch({type:'answer',id:q.id,value})}/><span>{text}</span></label>)}</fieldset><button className="button secondary compact" type="submit" disabled={!Number.isInteger(state.answers[q.id])||state.checked[q.id]}>بررسی پاسخ</button>{state.checked[q.id]?<p className={'dist-check-feedback '+(state.answers[q.id]===q.correct?'correct':'retry')} role="status">{q.feedback[state.answers[q.id]]}</p>:null}</form>)}</section>
 <section className="dist-card"><h2>ضریب را کنار نمودار تفسیر کن</h2><p>پیرسون رابطهٔ خطی مقدارهای کمی را خلاصه می‌کند. اسپیرمن روند یک‌جهتهٔ رتبه‌ها را می‌سنجد: با افزایش یکی، دیگری معمولاً بالا یا پایین می‌رود. اگر رابطه ابتدا کاهشی و سپس افزایشی باشد، حتی هر دو ضریب می‌توانند صفر شوند؛ مثال خمیده را ببین.</p><p>رتبه‌گذاری اثر فاصله‌های عددی را عوض می‌کند، اما تضمین نمی‌کند نتیجه در برابر همهٔ مقدارهای دور یا تغییر جفت‌ها ثابت بماند. همبستگی، درصد افراد یا احتمال درست‌بودن فرضیه نیست و به‌تنهایی علت را اثبات نمی‌کند. این ابزار فقط توصیفی است؛ آزمون معنی‌داری، فاصلهٔ اطمینان یا کندال محاسبه نمی‌کند.</p><div className="dist-actions"><button className="button secondary" onClick={onDownload}>دریافت گزارش رابطهٔ رتبه‌ها</button><button className="text-button" onClick={()=>navigate('lesson',9,{section:'guide-idea'})}>مرور مفهوم رابطه در درس نهم</button><button className="text-button" onClick={()=>navigate('lab',0,{mode:'ordinal'})}>فراوانی یک متغیر ترتیبی</button></div><div className="rank-sources"><a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/cor.html" target="_blank" rel="noreferrer">تعریف اسپیرمن · R</a><a href="https://stat.ethz.ch/R-manual/R-devel/library/base/html/rank.html" target="_blank" rel="noreferrer">رتبه‌های متوسط در تساوی‌ها · R</a><a href="https://www.itl.nist.gov/div898/handbook/eda/section3/scatterp.htm" target="_blank" rel="noreferrer">شکل رابطه و محدودیت علیت · NIST</a></div></section>
 </section>;
}
export default function RankCorrelation({navigate=()=>{}}){const [state,dispatch]=useReducer(rankReducer,undefined,initialRankState);function download(){const url=URL.createObjectURL(new Blob(['\uFEFF'+buildRankReport(state)],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='amar-rank-correlation.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}return <RankWorkspace state={state} dispatch={dispatch} navigate={navigate} onDownload={download}/>;}
