import React,{useReducer,useEffect,useRef} from 'react';
import {reportCases,createReportState,reportAttempt,reportReducer,reportSummary} from './reportCritique.js';
import {number} from './format.js';
import './reportCritique.css';

export function ReportWorkspace({state,dispatch,navigate}){
 const item=reportCases.find(c=>c.id===state.selected),attempt=reportAttempt(state),summary=reportSummary(state),position=reportCases.indexOf(item);
 const complete=attempt.results.every(r=>r?.correct);
 return <div className="report-page"><div className="page-heading"><h1>گزارش را نقد کن</h1><p>عدد درست کافی نیست؛ از داده چه نتیجه‌ای می‌توان گرفت؟</p></div>
  <p className="report-intro">ده مثال ساختگی را در دو گام بررسی کن: ایراد گزارش را پیدا کن، سپس جملهٔ دقیق‌تر را انتخاب کن. هر گزینه توضیح مخصوص خود را دارد.</p>
  <div className="report-summary" aria-label="جمع‌بندی همین تلاش‌ها"><span><strong>{number(summary.completed)} از {number(summary.total)}</strong> مثال با دو پاسخ درست</span><span><strong>{number(summary.beforeSolution)}</strong> پیش از دیدن پاسخ معیار</span><span><strong>{number(summary.withSolution)}</strong> با استفاده از پاسخ معیار</span></div>
  <p className="small-note">این شمارش ارزیابی جامع تسلط نیست. انتخاب‌ها فقط تا زمان حضور در این صفحه حفظ می‌شوند؛ با خروج یا بارگذاری دوباره پاک می‌شوند، در پشتیبان نیستند و پیشرفت درس‌ها یا بانک تمرین را تغییر نمی‌دهند.</p>
  <label className="report-selector" htmlFor="report-case">انتخاب مثال<select id="report-case" value={item.id} onChange={e=>dispatch({type:'select',id:e.target.value})}>{reportCases.map((c,i)=><option key={c.id} value={c.id}>{number(i+1)} · {c.title}{reportAttempt(state,c.id).results.every(r=>r?.correct)?' · بررسی شد':''}</option>)}</select></label>
  <article className="report-case"><div className="report-case-top"><span>مثال {number(position+1)} از ۱۰ · جلسهٔ {number(item.lesson)}</span><span>دادهٔ ساختگی</span></div><h2 id="report-case-title" tabIndex="-1">{item.title}</h2><p>{item.context}</p><div className="report-data"><strong>اطلاعات مسئله</strong><p>{item.data}</p></div><div className="report-claim"><strong>گزارش نیازمند اصلاح</strong><blockquote>{item.claim}</blockquote></div>
   <div className="report-steps">{item.steps.map((s,index)=>{const locked=index===1&&!attempt.results[0]?.correct,result=attempt.results[index];return <form key={item.id+'-'+index} onSubmit={e=>{e.preventDefault();dispatch({type:'check',step:index});}}><fieldset disabled={locked}><legend><span className="report-step-number">{number(index+1)}</span>{index===0?'ایراد را پیدا کن':'جمله را اصلاح کن'}</legend><p>{s.prompt}</p>{s.options.map((o,choice)=><label key={choice} className={'report-option '+(attempt.answers[index]===choice?'selected':'')}><input type="radio" name={'report-step-'+index} value={choice} checked={attempt.answers[index]===choice} onChange={()=>dispatch({type:'answer',step:index,choice})}/><span>{o.text}</span></label>)}<button type="submit" className="button secondary" disabled={attempt.answers[index]===null||Boolean(result)}>بررسی گام {number(index+1)}</button></fieldset>{locked?<p className="small-note">این گام پس از پاسخ درست به گام اول باز می‌شود. برای شروع، یک گزینه انتخاب کن یا پاسخ معیار را ببین.</p>:null}{result?<div className={'report-feedback '+(result.correct?'correct':'retry')} role="status"><strong>{result.correct?'درست است':'این برداشت را دوباره بررسی کن'}</strong><p>{s.options[result.choice].feedback}</p>{result.correct?<small>{result.assisted?'پاسخ درست پس از دیدن پاسخ معیار':'پاسخ درست پیش از دیدن پاسخ معیار'}</small>:<small>می‌توانی گزینه را عوض کنی و دوباره بررسی کنی.</small>}</div>:null}</form>;})}</div>
   {complete?<p className="report-complete" role="status">هر دو گام بررسی شد. {attempt.results.some(r=>r.assisted)?'در این تلاش از پاسخ معیار استفاده کردی.':'هر دو پاسخ را پیش از دیدن پاسخ معیار بررسی کردی.'}</p>:null}
   <div className="report-actions"><button className="text-button" aria-expanded={attempt.seen} aria-controls="report-solution" disabled={attempt.seen} onClick={()=>dispatch({type:'reveal'})}>{attempt.seen?'پاسخ معیار نمایش داده شد':'نمایش پاسخ معیار و توضیح'}</button><button className="text-button" onClick={()=>dispatch({type:'reset'})}>شروع تلاش تازه برای همین مثال</button></div>
   <p className="small-note">نمایش پاسخ معیار، جواب هر دو گام را آشکار می‌کند. پاسخ‌های درستِ بررسی‌شده پیش از آن حفظ می‌شوند؛ بررسی‌های بعد از آن «با پاسخ معیار» ثبت می‌شوند. تغییر پاسخ گام اول، بررسی گام دوم را پاک می‌کند ولی انتخاب قبلی و سابقهٔ دیدن پاسخ باقی می‌ماند. تلاش تازه از ابتدا شمرده می‌شود.</p>
   {attempt.seen?<section id="report-solution" className="report-solution"><h3>چرا این اصلاح دقیق‌تر است؟</h3><p><strong>ایراد:</strong> {item.steps[0].options[item.steps[0].correct].text}</p><p><strong>گزارش اصلاح‌شده:</strong> {item.steps[1].options[item.steps[1].correct].text}</p><p>{item.explanation}</p>{item.source?<a href={item.source.url} target="_blank" rel="noreferrer">منبع برای مطالعه: {item.source.label}</a>:null}<p className="small-note">پس از خواندن، گزینهٔ درست هر گام را انتخاب و بررسی کن؛ نمایش پاسخ به‌تنهایی مثال را کامل نمی‌کند.</p></section>:null}
   <div className="report-links"><button className="button secondary" onClick={()=>navigate('lesson',item.lesson,{section:'guide-idea'})}>مرور مفهوم در جلسهٔ {number(item.lesson)}</button>{item.mode?<button className="button secondary" onClick={()=>navigate('lab',0,{mode:item.mode})}>آزمایش مفهوم در ابزار</button>:null}<button className="text-button" onClick={()=>navigate('practice',item.lesson)}>تمرین‌های این جلسه</button></div>
  </article>
  <nav className="pagination" aria-label="مثال‌های نقد گزارش"><button className="button secondary" disabled={position===0} onClick={()=>dispatch({type:'select',id:reportCases[position-1].id})}>مثال قبل</button><span>{number(position+1)} / ۱۰</span><button className="button secondary" disabled={position===reportCases.length-1} onClick={()=>dispatch({type:'select',id:reportCases[position+1].id})}>مثال بعد</button></nav>
 </div>;
}
export default function ReportCritique({initialLesson=0,navigate}){
 const [state,dispatch]=useReducer(reportReducer,initialLesson,createReportState),previous=useRef(state.selected);
 useEffect(()=>{if(previous.current===state.selected)return;previous.current=state.selected;const heading=document.getElementById('report-case-title');heading?.scrollIntoView({block:'start'});heading?.focus({preventScroll:true});},[state.selected]);
 return <ReportWorkspace state={state} dispatch={dispatch} navigate={navigate}/>;
}
