import React,{useState} from 'react';
import {ArrowLeft,RotateCcw} from 'lucide-react';
import {fmt,number} from './format.js';
import {meanExamples,summarizeWeightedMean,validateMeanRow} from './weightedMean.js';

const rowName=(kind,i)=>(kind==='pooled'?'گروه ':'مقدار ')+['الف','ب','پ'][i];
const labels={weighted:{value:'مقدار',weight:'وزن',mean:'میانگین وزنی'},pooled:{value:'میانگین گروه',weight:'تعداد افراد',mean:'میانگین همهٔ افراد'}};
export function MeanEditor({rows,kind,onChange}){
  return <div className="mean-input-rows">{rows.map((row,i)=>{const valid=validateMeanRow(row,kind);return <fieldset key={i}><legend>{rowName(kind,i)}</legend><label>{labels[kind].value}<input type="text" inputMode="decimal" value={row.value} aria-invalid={valid.valueError} aria-describedby="mean-input-help" onChange={e=>onChange(i,'value',e.target.value)}/></label><label>{labels[kind].weight}<input type="text" inputMode={kind==='pooled'?'numeric':'decimal'} value={row.weight} aria-invalid={valid.weightError} aria-describedby="mean-input-help" onChange={e=>onChange(i,'weight',e.target.value)}/></label>{valid.weight===0&&!valid.weightError?<small>سهم این ردیف صفر است؛ در نتیجه وارد نمی‌شود.</small>:null}</fieldset>;})}</div>;
}
export function MeanResults({result,kind}){
  const hasMean=result.mean!==null;
  const low=result.min===result.max?result.min-1:result.min,high=result.min===result.max?result.max+1:result.max;
  const position=value=>55+470*(value-low)/(high-low);
  return <>
    <section className="mean-card"><h2>چه چیزی سهم بیشتری دارد؟</h2><div className="mean-metrics"><div><span>{labels[kind].mean}</span><strong data-testid="weighted-mean">{fmt(result.mean)}</strong></div><div><span>{kind==='pooled'?'میانگین گروه‌های غیرخالی با سهم برابر':'میانگین مقدارهای دارای وزن مثبت با سهم برابر'}</span><strong>{fmt(result.equalMean)}</strong></div></div>{hasMean?<><div className="mean-shares" aria-hidden="true">{result.rows.map((row,i)=>row.share>0?<span key={i} className={'mean-color-'+i} style={{width:row.share*100+'%'}}/>:null)}</div><ul className="mean-share-labels">{result.rows.map((row,i)=><li key={i}><i className={'mean-color-'+i}/>{rowName(kind,i)}: {row.share===null?'تعریف‌نشده':fmt(row.share*100)+'٪'}</li>)}</ul><figure className="mean-position"><svg viewBox="0 0 580 185" role="img" aria-label={`روی مقیاس مشترک از ${fmt(low)} تا ${fmt(high)}، ${labels[kind].mean} ${fmt(result.mean)} و میانگین با سهم برابر ${fmt(result.equalMean)} است.`}>{[65,135].map((y,i)=><g key={y}><line x1="55" x2="525" y1={y} y2={y}/><circle cx={position(i===0?result.mean:result.equalMean)} cy={y} r="8" className={i===0?'mean-weighted-dot':'mean-equal-dot'}/><text x="290" y={y-22} textAnchor="middle">{i===0?labels[kind].mean:'با سهم برابر'}: {fmt(i===0?result.mean:result.equalMean)}</text></g>)}{[low,high].map((value,i)=><text x={i===0?55:525} y="173" textAnchor="middle" key={i}>{fmt(value)}</text>)}</svg><figcaption>هر دو نشانگر روی یک مقیاس‌اند. نتیجهٔ وزنی بین کوچک‌ترین و بزرگ‌ترین مقدارِ دارای وزن مثبت می‌ماند.</figcaption></figure><p className="insight">{kind==='pooled'?`برای توصیف همهٔ ${number(result.totalWeight)} نفر، میانگین ترکیبی ${fmt(result.mean)} است. سهم هر گروه به تعداد افرادش بستگی دارد.`:`مجموع وزن‌ها ${fmt(result.totalWeight)} است؛ پس مجموع حاصل‌ضرب‌ها را بر ${fmt(result.totalWeight)} تقسیم می‌کنیم، نه تعداد ردیف‌ها.`}</p></>:<p className="insight" role="status">همهٔ وزن‌ها صفرند؛ مخرج صفر است و میانگین تعریف نمی‌شود. دست‌کم یک وزن مثبت لازم است.</p>}<p className="small-note">میانگین با سهم برابر به سؤال دیگری پاسخ می‌دهد: اگر هر ردیفِ دارای وزن مثبت به یک اندازه سهم داشت، نتیجه چه می‌شد؟ برابرشدن دو نتیجه به‌تنهایی ثابت نمی‌کند که وزن‌ها برابرند.</p></section>
    <section className="mean-card"><h2>محاسبه را دنبال کن</h2><div className="mean-formula" dir="ltr">{kind==='pooled'?'x̄ = Σ(nᵢ × x̄ᵢ) / Σnᵢ':'x̄w = Σ(wᵢ × xᵢ) / Σwᵢ'}</div><p>{kind==='pooled'?'میانگین هر گروه × تعداد افراد آن، مجموع مقدارهای همان گروه را بازسازی می‌کند. مجموعِ گروه‌ها را بر تعداد کل افراد تقسیم کن.':'هر مقدار را در وزنش ضرب کن؛ حاصل‌ضرب‌ها را جمع کن؛ سپس بر مجموع وزن‌ها تقسیم کن.'}</p><div className="table-scroll" role="region" aria-label="جدول محاسبهٔ میانگین وزنی" tabIndex="0"><table className="mean-table"><caption>عددهای هر ردیف و سهم آن در محاسبه</caption><thead><tr><th scope="col">ردیف</th><th scope="col">{labels[kind].value}</th><th scope="col">{labels[kind].weight}</th><th scope="col">حاصل‌ضرب</th><th scope="col">سهم از وزن کل</th></tr></thead><tbody>{result.rows.map((row,i)=><tr key={i}><th scope="row">{rowName(kind,i)}</th><td>{fmt(row.value)}</td><td>{fmt(row.weight)}</td><td>{fmt(row.product)}{row.weight===0?<small>بدون سهم</small>:null}</td><td>{row.share===null?'تعریف‌نشده':fmt(100*row.share)+'٪'}</td></tr>)}</tbody><tfoot><tr><th scope="row">مجموع</th><td>—</td><td>{fmt(result.totalWeight)}</td><td>{fmt(result.weightedSum)}</td><td>{hasMean?'۱۰۰٪':'تعریف‌نشده'}</td></tr></tfoot></table></div><div className="mean-equation" aria-live="polite">{hasMean?`${fmt(result.weightedSum)} ÷ ${fmt(result.totalWeight)} = ${fmt(result.mean)}`:'۰ ÷ ۰ → تعریف‌نشده'}</div><p className="small-note">محاسبه پیش از گردکردن انجام می‌شود؛ نمایش تا دو رقم اعشار است. ممکن است جمع درصدهای نمایشی دقیقاً ۱۰۰ نشود. {kind==='pooled'?'اگر میانگین گروه‌ها از قبل گرد شده باشند، نتیجهٔ ترکیبی نیز تقریبی است.':''}</p></section>
  </>;
}
export const meanChecks={
  weighted:{question:'اگر همهٔ وزن‌های مثبت را دو برابر کنیم و مقدارها ثابت بمانند، میانگین وزنی چه می‌شود؟',options:['دو برابر می‌شود','تغییر نمی‌کند','نصف می‌شود'],correct:1,feedback:['صورت و مخرج هر دو دو برابر می‌شوند؛ نسبتشان و میانگین ثابت می‌ماند.','درست است: نسبت وزن‌ها ثابت می‌ماند. مثلاً وزن‌های ۱، ۳، ۲ همان نتیجهٔ ۲، ۶، ۴ را می‌دهند.','فقط مخرج تغییر نمی‌کند؛ صورت هم دو برابر می‌شود. پس نسبت و میانگین ثابت است.']},
  pooled:{question:'گروه الف: ۱۰ نفر با میانگین ۱۰؛ گروه ب: ۳۰ نفر با میانگین ۱۸. برای میانگین همهٔ ۴۰ نفر، مجموع ۶۴۰ را بر چه چیزی تقسیم می‌کنیم؟',options:['۲ گروه','۴۰ نفر','۳۰ نفرِ گروه بزرگ‌تر'],correct:1,feedback:['۲ شمار گروه‌هاست؛ ۶۴۰ مجموع نمره‌های افراد است و باید بر تعداد کل ۴۰ نفر تقسیم شود؛ ۶۴۰ ÷ ۴۰ = ۱۶.','درست است: ۱۰ × ۱۰ + ۳۰ × ۱۸ = ۶۴۰؛ سپس ۶۴۰ ÷ ۴۰ = ۱۶. میانگین سادهٔ ۱۰ و ۱۸ برابر ۱۴ است و همهٔ افراد را توصیف نمی‌کند.','۳۰ فقط تعداد افراد گروه ب است، اما صورت ۶۴۰ هر دو گروه را شامل می‌شود. مخرج هم باید تعداد افراد هر دو گروه، یعنی ۴۰، باشد تا نتیجه ۱۶ شود.']},
};
export function MeanCheck({kind,answer,onAnswer}){
  const check=meanChecks[kind];
  return <section className="mean-card"><h2>قبل از فرمول، سهم‌ها را بفهم</h2><p>{check.question}</p><div className="mean-check-options">{check.options.map((label,i)=><button className="button secondary" key={label} aria-pressed={answer===i} onClick={()=>onAnswer(i)}>{label}</button>)}</div>{answer!==null?<p className="insight" role="status">{check.feedback[answer]}</p>:null}<p className="small-note">این تمرین برای یادگیری همین بخش است؛ پاسخ آن در پیشرفت دوره ذخیره نمی‌شود.</p></section>;
}
export default function WeightedMean(){
  const [kind,setKind]=useState('weighted'),[drafts,setDrafts]=useState(()=>Object.fromEntries(Object.entries(meanExamples).map(([id,example])=>[id,example.rows.map(row=>({...row}))]))),[answers,setAnswers]=useState({weighted:null,pooled:null});
  const rows=drafts[kind],result=summarizeWeightedMean(rows,kind);
  function update(index,key,value){setDrafts(current=>({...current,[kind]:current[kind].map((row,i)=>i===index?{...row,[key]:value}:row)}));}
  function changeWeights(equal){if(!equal&&!result)return;setDrafts(current=>({...current,[kind]:current[kind].map((row,i)=>({...row,weight:equal?(kind==='pooled'?'10':'1'):String(result.rows[i].weight*2)}))}));}
  const canDouble=Boolean(result&&result.rows.every(row=>row.weight<=500000));
  return <section id="lab-panel" role="tabpanel" aria-labelledby="tab-weighted" className="mean-lab">
    <header className="mean-opening"><span className="lesson-eyebrow">هر مقدار چقدر سهم دارد؟</span><h2>میانگین فقط جمع و تقسیم نیست؛ سهم‌ها را بشناس.</h2><p>در میانگین ساده، هر مشاهده سهم برابر دارد. اگر سهم‌ها متفاوت‌اند، وزن هر مقدار را وارد کن. برای ترکیب میانگین گروه‌ها، تعداد افراد همان وزن است.</p><div className="mean-kind-buttons" role="group" aria-label="نوع مثال میانگین">{[['weighted','مقدارها و وزن‌ها'],['pooled','ترکیب میانگین گروه‌ها']].map(([id,label])=><button className="button secondary" key={id} aria-pressed={kind===id} onClick={()=>setKind(id)}>{label}</button>)}</div><p className="small-note">دو مثالِ ساختگی‌اند؛ با جابه‌جایی بین آن‌ها، ورودی‌های تغییرکرده در همین بخش حفظ می‌شوند.</p></header>
    <div className="mean-workspace"><aside className="mean-card mean-editor"><h2>{meanExamples[kind].title}</h2><p>{kind==='weighted'?'نمونهٔ اولیه: نمره‌های ۱۲، ۱۸ و ۱۶ با وزنِ واحدهای ۱، ۳ و ۲. نمره‌ها در یک مقیاس‌اند و واحد هر درس سهم آن را تعیین می‌کند.':'نمونهٔ اولیه: گروه الف ۱۰ نفر با میانگین ۱۰ و گروه ب ۳۰ نفر با میانگین ۱۸. هر نفر دقیقاً در یک گروه و مقدارها در یک مقیاس‌اند.'}</p><MeanEditor rows={rows} kind={kind} onChange={update}/><p id="mean-input-help" className="small-note">مقدارها بین منفی و مثبت ۱٬۰۰۰٬۰۰۰؛ وزن‌ها بین صفر و ۱٬۰۰۰٬۰۰۰. ارقام فارسی و اعشار «٫» تا شش رقم اعشار پذیرفته می‌شوند. {kind==='pooled'?'تعداد افراد باید صحیح باشد. برای گروه با تعداد صفر، میانگین می‌تواند خالی بماند.':'وزن می‌تواند اعشاری باشد. با وزن صفر، مقدار می‌تواند خالی بماند.'} ورودی خالی با صفر جایگزین نمی‌شود.</p>{!result?<p role="alert" className="error-message">ورودی مشخص‌شده را اصلاح کن. وزن منفی و مقدار نامعتبر پذیرفته نمی‌شوند. {kind==='pooled'?'تعداد افراد باید صحیح باشد.':null}</p>:null}<div className="mean-editor-actions"><button className="button secondary" onClick={()=>changeWeights(true)}>{kind==='pooled'?'اندازهٔ هر دو گروه را ۱۰ کن':'همهٔ وزن‌ها را ۱ کن'}</button><button className="button secondary" disabled={!canDouble} onClick={()=>changeWeights(false)}>همهٔ {kind==='pooled'?'تعدادها':'وزن‌ها'} را دو برابر کن</button><button className="text-button" onClick={()=>setDrafts(current=>({...current,[kind]:meanExamples[kind].rows.map(row=>({...row}))}))}><RotateCcw size={17}/>بازنشانی همین مثال</button></div><p className="small-note">برای دوبرابرکردن، ورودی‌ها باید معتبر و هر وزن حداکثر ۵۰۰٬۰۰۰ باشد.</p></aside><div className="mean-output">{result?<MeanResults result={result} kind={kind}/>:<div className="empty-state"><h2>منتظر مقدارها و وزن‌های معتبر</h2><p>پس از اصلاح ورودی، جدول و نتیجه به‌روز می‌شوند.</p></div>}</div></div>
    <MeanCheck kind={kind} answer={answers[kind]} onAnswer={answer=>setAnswers(current=>({...current,[kind]:answer}))}/>
    <section className="mean-card mean-limits"><h2>کِی می‌توانیم ترکیب کنیم؟</h2><ul><li>مقدارها باید واحد و مقیاس قابل مقایسه داشته باشند؛ میانگین ساعت خواب و نمرهٔ رضایت، یک مقدار معنادار نمی‌سازد.</li><li>برای میانگین همهٔ افراد، گروه‌ها باید جدا باشند و هر فرد فقط یک‌بار شمرده شود. تعداد هر گروه باید مربوط به همان مشاهده‌های معتبرِ میانگین آن گروه باشد.</li><li>با میانگین و تعداد گروه‌ها، میانگین کل به دست می‌آید؛ برای میانهٔ کل معمولاً دادهٔ خام یا توزیع داده‌ها لازم است؛ برای انحراف معیار کل، اطلاعات پراکندگی درون گروه‌ها هم لازم است.</li><li>وزن باید دلیل روشنی داشته باشد؛ تغییر دلخواه وزن‌ها برای رسیدن به جواب دلخواه، گزارش معتبری نیست.</li></ul><a className="guide-source" href="https://www.itl.nist.gov/div898/software/dataplot/refman2/ch2/weigmean.pdf" target="_blank" rel="noopener noreferrer">فرمول میانگین وزنی · NIST (PDF)<ArrowLeft size={16}/></a></section>
  </section>;
}
